/** @file     Rte_Dem.h
  *
  * @brief    Application header file
  *
  * @note     AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
  *
  * @note     Generated by ETAS RTA-RTE
  * @note     Version 6.4.0 
  *
  * @date     Sun Jul 29 21:33:08 2018
  */

#ifndef RTE_DEM_H
#define RTE_DEM_H

#ifndef RTE_CORE
#ifdef RTE_APPLICATION_HEADER_FILE
#error Multiple application header files included.
#endif /* RTE_APPLICATION_HEADER_FILE */
#define RTE_APPLICATION_HEADER_FILE
#endif /* RTE_CORE */

/*******************************************************
 ***
 *** Includes
 ***
 *******************************************************/

#include "Rte.h"
#include "Rte_Intl.h"
#include "Rte_Dem_Type.h"

#include "Rte_DataHandleType.h"

#ifdef __cplusplus
extern "C++" {
#endif /* __cplusplus */

#if defined(RTE_RUNNABLEAPI_ClearDTC)
   /* Do nothing for this and all elif clauses below (rte_sws_2751) */
#elif defined(RTE_RUNNABLEAPI_ClearPrestoredFreezeFrame)
#elif defined(RTE_RUNNABLEAPI_Dem_GetDTCOfEvent_GeneralEvtInfo)
#elif defined(RTE_RUNNABLEAPI_Dem_GetEventExtendedDataRecordEx_GeneralEvtInfo)
#elif defined(RTE_RUNNABLEAPI_Dem_GetEventExtendedDataRecord_GeneralEvtInfo)
#elif defined(RTE_RUNNABLEAPI_Dem_GetEventFailed_GeneralEvtInfo)
#elif defined(RTE_RUNNABLEAPI_Dem_GetEventFreezeFrameDataEx_GeneralEvtInfo)
#elif defined(RTE_RUNNABLEAPI_Dem_GetEventFreezeFrameData_GeneralEvtInfo)
#elif defined(RTE_RUNNABLEAPI_Dem_GetEventStatus_GeneralEvtInfo)
#elif defined(RTE_RUNNABLEAPI_Dem_GetEventTested_GeneralEvtInfo)
#elif defined(RTE_RUNNABLEAPI_Dem_GetFaultDetectionCounter_GeneralEvtInfo)
#elif defined(RTE_RUNNABLEAPI_Dem_MainFunction)
#elif defined(RTE_RUNNABLEAPI_GetCycleQualified)
#elif defined(RTE_RUNNABLEAPI_GetDTCOfEvent)
#elif defined(RTE_RUNNABLEAPI_GetDebouncingOfEvent)
#elif defined(RTE_RUNNABLEAPI_GetDebouncingOfEvent_GeneralEvtInfo)
#elif defined(RTE_RUNNABLEAPI_GetEventExtendedDataRecord)
#elif defined(RTE_RUNNABLEAPI_GetEventExtendedDataRecordEx)
#elif defined(RTE_RUNNABLEAPI_GetEventFailed)
#elif defined(RTE_RUNNABLEAPI_GetEventFreezeFrameData)
#elif defined(RTE_RUNNABLEAPI_GetEventFreezeFrameDataEx)
#elif defined(RTE_RUNNABLEAPI_GetEventMemoryOverflow)
#elif defined(RTE_RUNNABLEAPI_GetEventStatus)
#elif defined(RTE_RUNNABLEAPI_GetEventTested)
#elif defined(RTE_RUNNABLEAPI_GetFaultDetectionCounter)
#elif defined(RTE_RUNNABLEAPI_GetIndicatorStatus)
#elif defined(RTE_RUNNABLEAPI_GetNumberOfEventMemoryEntries)
#elif defined(RTE_RUNNABLEAPI_GetOperationCycleState)
#elif defined(RTE_RUNNABLEAPI_GetStorageCondition)
#elif defined(RTE_RUNNABLEAPI_PrestoreFreezeFrame)
#elif defined(RTE_RUNNABLEAPI_ResetEventDebounceStatus)
#elif defined(RTE_RUNNABLEAPI_ResetEventStatus)
#elif defined(RTE_RUNNABLEAPI_SetCycleQualified)
#elif defined(RTE_RUNNABLEAPI_SetDTCSuppression)
#elif defined(RTE_RUNNABLEAPI_SetEnableCondition)
#elif defined(RTE_RUNNABLEAPI_SetEventAvailable)
#elif defined(RTE_RUNNABLEAPI_SetEventStatus)
#elif defined(RTE_RUNNABLEAPI_SetOperationCycleState)
#elif defined(RTE_RUNNABLEAPI_SetStorageCondition)
#elif defined(RTE_RUNNABLEAPI_SetWIRStatus)
#else
   /* None of above defined so define value including all APIs (rte_sws_2751) */
   #define RTE_PRV_ALL_API
#endif

/*******************************************************
 ***
 *** Constants
 ***
 *******************************************************/

#ifndef RTE_CORE
#define RTE_E_CSDataServices_IgnitionCycles_E_NOT_OK ((Std_ReturnType)1)
#define RTE_E_CSDataServices_IgnitionCycles_E_OK ((Std_ReturnType)0)
#define RTE_E_CSDataServices_Milage_E_NOT_OK ((Std_ReturnType)1)
#define RTE_E_CSDataServices_Milage_E_OK ((Std_ReturnType)0)
#define RTE_E_CSDataServices_OccurenceCounter_E_NOT_OK ((Std_ReturnType)1)
#define RTE_E_CSDataServices_OccurenceCounter_E_OK ((Std_ReturnType)0)
#define RTE_E_CSDataServices_TemperaturEngine_E_NOT_OK ((Std_ReturnType)1)
#define RTE_E_CSDataServices_TemperaturEngine_E_OK ((Std_ReturnType)0)
#define RTE_E_CSDataServices_TemperaturOut_E_NOT_OK ((Std_ReturnType)1)
#define RTE_E_CSDataServices_TemperaturOut_E_OK ((Std_ReturnType)0)
#define RTE_E_CSDataServices_VehicleSpeed_i_E_NOT_OK ((Std_ReturnType)1)
#define RTE_E_CSDataServices_VehicleSpeed_i_E_OK ((Std_ReturnType)0)
#define RTE_E_CallbackClearEventAllowed_E_NOT_OK ((Std_ReturnType)1)
#define RTE_E_CallbackClearEventAllowed_E_OK ((Std_ReturnType)0)
#define RTE_E_CallbackDTCStatusChange_E_NOT_OK ((Std_ReturnType)1)
#define RTE_E_CallbackDTCStatusChange_E_OK ((Std_ReturnType)0)
#define RTE_E_CallbackGetFaultDetectCounter_DEM_E_NO_FDC_AVAILABLE ((Std_ReturnType)3)
#define RTE_E_CallbackGetFaultDetectCounter_E_NOT_OK ((Std_ReturnType)1)
#define RTE_E_CallbackGetFaultDetectCounter_E_OK ((Std_ReturnType)0)
#define RTE_E_CallbackInitMonitorForEvent_E_NOT_OK ((Std_ReturnType)1)
#define RTE_E_CallbackInitMonitorForEvent_E_OK ((Std_ReturnType)0)
#define RTE_E_CddIf_DEM_CLEAR_FAILED ((Std_ReturnType)3)
#define RTE_E_CddIf_DEM_CLEAR_MEMORY_ERROR ((Std_ReturnType)6)
#define RTE_E_CddIf_DEM_CLEAR_PENDING ((Std_ReturnType)4)
#define RTE_E_CddIf_DEM_CLEAR_WRONG_DTC ((Std_ReturnType)1)
#define RTE_E_CddIf_DEM_CLEAR_WRONG_DTCORIGIN ((Std_ReturnType)2)
#define RTE_E_DTCSuppression_E_NOT_OK ((Std_ReturnType)1)
#define RTE_E_DTCSuppression_E_OK ((Std_ReturnType)0)
#define RTE_E_DcmIf_DEM_CLEAR_BUSY ((Std_ReturnType)5)
#define RTE_E_DcmIf_DEM_CLEAR_FAILED ((Std_ReturnType)3)
#define RTE_E_DcmIf_DEM_CLEAR_MEMORY_ERROR ((Std_ReturnType)6)
#define RTE_E_DcmIf_DEM_CLEAR_PENDING ((Std_ReturnType)4)
#define RTE_E_DcmIf_DEM_CLEAR_WRONG_DTC ((Std_ReturnType)1)
#define RTE_E_DcmIf_DEM_CLEAR_WRONG_DTCORIGIN ((Std_ReturnType)2)
#define RTE_E_DcmIf_E_OK ((Std_ReturnType)0)
#define RTE_E_DiagnosticInfo_DEM_E_NO_DTC_AVAILABLE ((Std_ReturnType)2)
#define RTE_E_DiagnosticInfo_DEM_E_NO_FDC_AVAILABLE ((Std_ReturnType)3)
#define RTE_E_DiagnosticInfo_E_NOT_OK ((Std_ReturnType)1)
#define RTE_E_DiagnosticInfo_E_OK ((Std_ReturnType)0)
#define RTE_E_DiagnosticMonitor_E_NOT_OK ((Std_ReturnType)1)
#define RTE_E_DiagnosticMonitor_E_OK ((Std_ReturnType)0)
#define RTE_E_EnableCondition_E_NOT_OK ((Std_ReturnType)1)
#define RTE_E_EnableCondition_E_OK ((Std_ReturnType)0)
#define RTE_E_EvMemOverflowIndication_E_NOT_OK ((Std_ReturnType)1)
#define RTE_E_EvMemOverflowIndication_E_OK ((Std_ReturnType)0)
#define RTE_E_EventAvailable_E_NOT_OK ((Std_ReturnType)1)
#define RTE_E_EventAvailable_E_OK ((Std_ReturnType)0)
#define RTE_E_EventStatus_E_NOT_OK ((Std_ReturnType)1)
#define RTE_E_EventStatus_E_OK ((Std_ReturnType)0)
#define RTE_E_GeneralDiagnosticInfo_DEM_E_NO_DTC_AVAILABLE ((Std_ReturnType)2)
#define RTE_E_GeneralDiagnosticInfo_DEM_E_NO_FDC_AVAILABLE ((Std_ReturnType)3)
#define RTE_E_GeneralDiagnosticInfo_E_NOT_OK ((Std_ReturnType)1)
#define RTE_E_GeneralDiagnosticInfo_E_OK ((Std_ReturnType)0)
#define RTE_E_IndicatorStatus_E_NOT_OK ((Std_ReturnType)1)
#define RTE_E_IndicatorStatus_E_OK ((Std_ReturnType)0)
#define RTE_E_OperationCycle_E_NOT_OK ((Std_ReturnType)1)
#define RTE_E_OperationCycle_E_OK ((Std_ReturnType)0)
#define RTE_E_StorageCondition_E_NOT_OK ((Std_ReturnType)1)
#define RTE_E_StorageCondition_E_OK ((Std_ReturnType)0)
#endif /* RTE_CORE */

/*******************************************************
 ***
 *** Public Types
 ***
 *******************************************************/

/* BEGIN: SWC types (core visible) */
struct Rte_CDS_Dem {
   uint8 Rte_Dummy;
};
typedef struct Rte_CDS_Dem Rte_CDS_Dem;
/* END: SWC types (core visible) */

/*******************************************************
 ***
 *** Private Types
 ***
 *******************************************************/

/* BEGIN: SWC types (private) */
/* END: SWC types (private) */

/*******************************************************
 ***
 *** Instance Declarations
 ***
 *******************************************************/

#define RTE_START_SEC_CONST_UNSPECIFIED
#include "Rte_MemMap.h" /*lint !e537 permit multiple inclusion */
extern CONST(struct Rte_CDS_Dem, RTE_CONST) Rte_Inst_Dem;
#define RTE_STOP_SEC_CONST_UNSPECIFIED
#include "Rte_MemMap.h" /*lint !e537 permit multiple inclusion */


#ifndef RTE_CORE
typedef CONSTP2CONST(struct Rte_CDS_Dem, AUTOMATIC, RTE_CONST) Rte_Instance;
#endif /* RTE_CORE */

/*******************************************************
 ***
 *** API Mapping macros
 ***
 *******************************************************/

/* API Mapping Macros */
#ifndef RTE_CORE

#define RTE_START_SEC_CODE
#include "Rte_MemMap.h" /*lint !e537 permit multiple inclusion */
FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dem_CBClrEvt_Monitoring_01_ClearEventAllowed(P2VAR(boolean, AUTOMATIC, RTE_APPL_DATA) Allowed);
FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dem_CBClrEvt_Monitoring_29_ClearEventAllowed(P2VAR(boolean, AUTOMATIC, RTE_APPL_DATA) Allowed);
FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dem_CBFaultDetectCtr_Monitoring_01_GetFaultDetectionCounter(P2VAR(sint8, AUTOMATIC, RTE_APPL_DATA) FaultDetectionCounter);
FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dem_CBFaultDetectCtr_Monitoring_29_GetFaultDetectionCounter(P2VAR(sint8, AUTOMATIC, RTE_APPL_DATA) FaultDetectionCounter);
FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dem_CBInitEvt_Monitoring_01_InitMonitorForEvent(VAR(Dem_InitMonitorReasonType, AUTOMATIC) InitMonitorReason);
FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dem_CBInitEvt_Monitoring_15_InitMonitorForEvent(VAR(Dem_InitMonitorReasonType, AUTOMATIC) InitMonitorReason);
FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dem_CBInitEvt_Monitoring_16_InitMonitorForEvent(VAR(Dem_InitMonitorReasonType, AUTOMATIC) InitMonitorReason);
FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dem_CBReadData_IgnitionCycles_ReadData(P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) Data);
FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dem_CBReadData_Milage_ReadData(P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) Data);
FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dem_CBReadData_OccurenceCounter_ReadData(P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) Data);
FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dem_CBReadData_TemperaturEngine_ReadData(P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) Data);
FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dem_CBReadData_TemperaturOut_ReadData(P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) Data);
FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dem_CBReadData_VehicleSpeed_i_ReadData(P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) Data);
FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dem_CBStatusDTC_1_DTCStatusChanged(VAR(uint32, AUTOMATIC) DTC,
                                                                           VAR(Dem_UdsStatusByteType, AUTOMATIC) DTCStatusOld,
                                                                           VAR(Dem_UdsStatusByteType, AUTOMATIC) DTCStatusNew);
FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dem_CBStatusEvt_Monitoring_01_0_EventStatusChanged(VAR(Dem_UdsStatusByteType, AUTOMATIC) EventStatusOld,
                                                                                           VAR(Dem_UdsStatusByteType, AUTOMATIC) EventStatusNew);
FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dem_CBStatusEvt_Monitoring_27_0_EventStatusChanged(VAR(Dem_UdsStatusByteType, AUTOMATIC) EventStatusOld,
                                                                                           VAR(Dem_UdsStatusByteType, AUTOMATIC) EventStatusNew);
FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dem_CBStatusEvt_Monitoring_27_1_EventStatusChanged(VAR(Dem_UdsStatusByteType, AUTOMATIC) EventStatusOld,
                                                                                           VAR(Dem_UdsStatusByteType, AUTOMATIC) EventStatusNew);
FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dem_CBStatusEvt_Monitoring_29_0_EventStatusChanged(VAR(Dem_UdsStatusByteType, AUTOMATIC) EventStatusOld,
                                                                                           VAR(Dem_UdsStatusByteType, AUTOMATIC) EventStatusNew);
FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dem_GeneralCBDataEvt_EventDataChanged(VAR(Dem_EventIdType, AUTOMATIC) EventId);
FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dem_GeneralCBStatusEvt_EventStatusChanged(VAR(Dem_EventIdType, AUTOMATIC) EventId,
                                                                                  VAR(Dem_UdsStatusByteType, AUTOMATIC) EventStatusOld,
                                                                                  VAR(Dem_UdsStatusByteType, AUTOMATIC) EventStatusNew);
#define RTE_STOP_SEC_CODE
#include "Rte_MemMap.h" /*lint !e537 permit multiple inclusion */
#define RTE_START_SEC_CONST_UNSPECIFIED
#include "Rte_MemMap.h" /*lint !e537 permit multiple inclusion */
extern CONST(Rte_SelfType_Swc1, RTE_CONST) Rte_Self_SWCI0;
#define RTE_STOP_SEC_CONST_UNSPECIFIED
#include "Rte_MemMap.h" /*lint !e537 permit multiple inclusion */
#define Swc1_START_SEC_CODE
#include "Swc1_MemMap.h" /*lint !e537 permit multiple inclusion */
FUNC(void, Swc1_CODE) Swc1_CBStatusComp_node_a_l1(VAR(boolean, AUTOMATIC) ComponentFailedStatus);

FUNC(void, Swc1_CODE) Swc1_CBStatusComp_node_b_l1(VAR(boolean, AUTOMATIC) ComponentFailedStatus);

FUNC(void, Swc1_CODE) Swc1_CBStatusComp_node_c_l2(VAR(boolean, AUTOMATIC) ComponentFailedStatus);

FUNC(void, Swc1_CODE) Swc1_CBStatusComp_node_d_l3(VAR(boolean, AUTOMATIC) ComponentFailedStatus);

FUNC(void, Swc1_CODE) Swc1_CBStatusComp_node_e_l2(VAR(boolean, AUTOMATIC) ComponentFailedStatus);

FUNC(void, Swc1_CODE) Swc1_CBStatusComp_rootnode(VAR(boolean, AUTOMATIC) ComponentFailedStatus);

#define Swc1_STOP_SEC_CODE
#include "Swc1_MemMap.h" /*lint !e537 permit multiple inclusion */
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_Dem_MainFunction)
#define Rte_Call_CBClrEvt_Monitoring_01_ClearEventAllowed Rte_Call_Dem_CBClrEvt_Monitoring_01_ClearEventAllowed /* enableTakeAddress */
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_Dem_MainFunction)
#define Rte_Call_CBClrEvt_Monitoring_29_ClearEventAllowed Rte_Call_Dem_CBClrEvt_Monitoring_29_ClearEventAllowed /* enableTakeAddress */
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_Dem_MainFunction)
#define Rte_Call_CBFaultDetectCtr_Monitoring_01_GetFaultDetectionCounter Rte_Call_Dem_CBFaultDetectCtr_Monitoring_01_GetFaultDetectionCounter /* enableTakeAddress */
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_Dem_MainFunction)
#define Rte_Call_CBFaultDetectCtr_Monitoring_29_GetFaultDetectionCounter Rte_Call_Dem_CBFaultDetectCtr_Monitoring_29_GetFaultDetectionCounter /* enableTakeAddress */
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_Dem_MainFunction)
#define Rte_Call_CBInitEvt_Monitoring_01_InitMonitorForEvent Rte_Call_Dem_CBInitEvt_Monitoring_01_InitMonitorForEvent /* enableTakeAddress */
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_Dem_MainFunction)
#define Rte_Call_CBInitEvt_Monitoring_15_InitMonitorForEvent Rte_Call_Dem_CBInitEvt_Monitoring_15_InitMonitorForEvent /* enableTakeAddress */
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_Dem_MainFunction)
#define Rte_Call_CBInitEvt_Monitoring_16_InitMonitorForEvent Rte_Call_Dem_CBInitEvt_Monitoring_16_InitMonitorForEvent /* enableTakeAddress */
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_Dem_MainFunction)
#define Rte_Call_CBReadData_IgnitionCycles_ReadData Rte_Call_Dem_CBReadData_IgnitionCycles_ReadData /* enableTakeAddress */
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_Dem_MainFunction)
#define Rte_Call_CBReadData_Milage_ReadData Rte_Call_Dem_CBReadData_Milage_ReadData /* enableTakeAddress */
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_Dem_MainFunction)
#define Rte_Call_CBReadData_OccurenceCounter_ReadData Rte_Call_Dem_CBReadData_OccurenceCounter_ReadData /* enableTakeAddress */
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_Dem_MainFunction)
#define Rte_Call_CBReadData_TemperaturEngine_ReadData Rte_Call_Dem_CBReadData_TemperaturEngine_ReadData /* enableTakeAddress */
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_Dem_MainFunction)
#define Rte_Call_CBReadData_TemperaturOut_ReadData Rte_Call_Dem_CBReadData_TemperaturOut_ReadData /* enableTakeAddress */
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_Dem_MainFunction)
#define Rte_Call_CBReadData_VehicleSpeed_i_ReadData Rte_Call_Dem_CBReadData_VehicleSpeed_i_ReadData /* enableTakeAddress */
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_Dem_MainFunction)
/* Inline function call optimization; Rte_Call_CBStatusComp_node_a_l1_ComponentStatusChanged to Swc1_CBStatusComp_node_a_l1 */
#define Rte_Call_CBStatusComp_node_a_l1_ComponentStatusChanged( ComponentFailedStatus ) ( Swc1_CBStatusComp_node_a_l1(ComponentFailedStatus), ((VAR(Std_ReturnType, AUTOMATIC))RTE_E_OK) )

#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_Dem_MainFunction)
/* Inline function call optimization; Rte_Call_CBStatusComp_node_b_l1_ComponentStatusChanged to Swc1_CBStatusComp_node_b_l1 */
#define Rte_Call_CBStatusComp_node_b_l1_ComponentStatusChanged( ComponentFailedStatus ) ( Swc1_CBStatusComp_node_b_l1(ComponentFailedStatus), ((VAR(Std_ReturnType, AUTOMATIC))RTE_E_OK) )

#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_Dem_MainFunction)
/* Inline function call optimization; Rte_Call_CBStatusComp_node_c_l2_ComponentStatusChanged to Swc1_CBStatusComp_node_c_l2 */
#define Rte_Call_CBStatusComp_node_c_l2_ComponentStatusChanged( ComponentFailedStatus ) ( Swc1_CBStatusComp_node_c_l2(ComponentFailedStatus), ((VAR(Std_ReturnType, AUTOMATIC))RTE_E_OK) )

#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_Dem_MainFunction)
/* Inline function call optimization; Rte_Call_CBStatusComp_node_d_l3_ComponentStatusChanged to Swc1_CBStatusComp_node_d_l3 */
#define Rte_Call_CBStatusComp_node_d_l3_ComponentStatusChanged( ComponentFailedStatus ) ( Swc1_CBStatusComp_node_d_l3(ComponentFailedStatus), ((VAR(Std_ReturnType, AUTOMATIC))RTE_E_OK) )

#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_Dem_MainFunction)
/* Inline function call optimization; Rte_Call_CBStatusComp_node_e_l2_ComponentStatusChanged to Swc1_CBStatusComp_node_e_l2 */
#define Rte_Call_CBStatusComp_node_e_l2_ComponentStatusChanged( ComponentFailedStatus ) ( Swc1_CBStatusComp_node_e_l2(ComponentFailedStatus), ((VAR(Std_ReturnType, AUTOMATIC))RTE_E_OK) )

#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_Dem_MainFunction)
/* Inline function call optimization; Rte_Call_CBStatusComp_rootnode_ComponentStatusChanged to Swc1_CBStatusComp_rootnode */
#define Rte_Call_CBStatusComp_rootnode_ComponentStatusChanged( ComponentFailedStatus ) ( Swc1_CBStatusComp_rootnode(ComponentFailedStatus), ((VAR(Std_ReturnType, AUTOMATIC))RTE_E_OK) )

#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_Dem_MainFunction)
#define Rte_Call_CBStatusDTC_1_DTCStatusChanged Rte_Call_Dem_CBStatusDTC_1_DTCStatusChanged /* enableTakeAddress */
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_Dem_MainFunction)
#define Rte_Call_CBStatusEvt_Monitoring_01_0_EventStatusChanged Rte_Call_Dem_CBStatusEvt_Monitoring_01_0_EventStatusChanged /* enableTakeAddress */
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_Dem_MainFunction)
#define Rte_Call_CBStatusEvt_Monitoring_27_0_EventStatusChanged Rte_Call_Dem_CBStatusEvt_Monitoring_27_0_EventStatusChanged /* enableTakeAddress */
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_Dem_MainFunction)
#define Rte_Call_CBStatusEvt_Monitoring_27_1_EventStatusChanged Rte_Call_Dem_CBStatusEvt_Monitoring_27_1_EventStatusChanged /* enableTakeAddress */
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_Dem_MainFunction)
#define Rte_Call_CBStatusEvt_Monitoring_29_0_EventStatusChanged Rte_Call_Dem_CBStatusEvt_Monitoring_29_0_EventStatusChanged /* enableTakeAddress */
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_Dem_MainFunction)
#define Rte_Call_GeneralCBDataEvt_EventDataChanged Rte_Call_Dem_GeneralCBDataEvt_EventDataChanged /* enableTakeAddress */
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_Dem_MainFunction)
#define Rte_Call_GeneralCBStatusEvt_EventStatusChanged Rte_Call_Dem_GeneralCBStatusEvt_EventStatusChanged /* enableTakeAddress */
#endif

#endif /* RTE_CORE */

/*******************************************************
 ***
 *** RE Prototypes
 ***
 *******************************************************/

#define Dem_START_SEC_CODE
#include "Dem_MemMap.h" /*lint !e537 permit multiple inclusion */
FUNC(Std_ReturnType, Dem_CODE) Dem_ClearDTC(VAR(uint32, AUTOMATIC) DTC,
                                            VAR(Dem_DTCFormatType, AUTOMATIC) DTCFormat,
                                            VAR(Dem_DTCOriginType, AUTOMATIC) DTCOrigin);
FUNC(Std_ReturnType, Dem_CODE) Dem_ClearPrestoredFreezeFrame(VAR(Dem_EventIdType, AUTOMATIC) Rte_PDAV0);
FUNC(Std_ReturnType, Dem_CODE) Dem_GetCycleQualified(VAR(Dem_OperationCycleIdType, AUTOMATIC) Rte_PDAV0,
                                                     P2VAR(boolean, AUTOMATIC, RTE_APPL_DATA) CycleState);
FUNC(Std_ReturnType, Dem_CODE) Dem_GetDTCOfEvent(VAR(Dem_EventIdType, AUTOMATIC) Rte_PDAV0,
                                                 VAR(Dem_DTCFormatType, AUTOMATIC) DTCFormat,
                                                 P2VAR(uint32, AUTOMATIC, RTE_APPL_DATA) DTCOfEvent);
FUNC(Std_ReturnType, Dem_CODE) Dem_GetDTCOfEvent_GeneralEvtInfo(VAR(Dem_EventIdType, AUTOMATIC) EventId,
                                                                VAR(Dem_DTCFormatType, AUTOMATIC) DTCFormat,
                                                                P2VAR(uint32, AUTOMATIC, RTE_APPL_DATA) DTCOfEvent);
FUNC(Std_ReturnType, Dem_CODE) Dem_GetDebouncingOfEvent(VAR(Dem_EventIdType, AUTOMATIC) Rte_PDAV0,
                                                        P2VAR(Dem_DebouncingStateType, AUTOMATIC, RTE_APPL_DATA) DebouncingState);
FUNC(Std_ReturnType, Dem_CODE) Dem_GetDebouncingOfEvent_GeneralEvtInfo(VAR(Dem_EventIdType, AUTOMATIC) EventId,
                                                                       P2VAR(Dem_DebouncingStateType, AUTOMATIC, RTE_APPL_DATA) DebouncingState);
FUNC(Std_ReturnType, Dem_CODE) Dem_GetEventExtendedDataRecordEx(VAR(Dem_EventIdType, AUTOMATIC) Rte_PDAV0,
                                                                VAR(uint8, AUTOMATIC) RecordNumber,
                                                                P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) DestBuffer,
                                                                P2VAR(uint16, AUTOMATIC, RTE_APPL_DATA) Bufsize);
FUNC(Std_ReturnType, Dem_CODE) Dem_GetEventExtendedDataRecordEx_GeneralEvtInfo(VAR(Dem_EventIdType, AUTOMATIC) EventId,
                                                                               VAR(uint8, AUTOMATIC) RecordNumber,
                                                                               P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) DestBuffer,
                                                                               P2VAR(uint16, AUTOMATIC, RTE_APPL_DATA) Bufsize);
FUNC(Std_ReturnType, Dem_CODE) Dem_GetEventExtendedDataRecordForRTE(VAR(Dem_EventIdType, AUTOMATIC) Rte_PDAV0,
                                                                    VAR(uint8, AUTOMATIC) RecordNumber,
                                                                    P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) DestBuffer);
FUNC(Std_ReturnType, Dem_CODE) Dem_GetEventExtendedDataRecord_GeneralEvtInfo(VAR(Dem_EventIdType, AUTOMATIC) EventId,
                                                                             VAR(uint8, AUTOMATIC) RecordNumber,
                                                                             P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) DestBuffer);
FUNC(Std_ReturnType, Dem_CODE) Dem_GetEventFailed(VAR(Dem_EventIdType, AUTOMATIC) Rte_PDAV0,
                                                  P2VAR(boolean, AUTOMATIC, RTE_APPL_DATA) EventFailed);
FUNC(Std_ReturnType, Dem_CODE) Dem_GetEventFailed_GeneralEvtInfo(VAR(Dem_EventIdType, AUTOMATIC) EventId,
                                                                 P2VAR(boolean, AUTOMATIC, RTE_APPL_DATA) EventFailed);
FUNC(Std_ReturnType, Dem_CODE) Dem_GetEventFreezeFrameDataEx(VAR(Dem_EventIdType, AUTOMATIC) Rte_PDAV0,
                                                             VAR(uint8, AUTOMATIC) RecordNumber,
                                                             VAR(uint16, AUTOMATIC) DataId,
                                                             P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) DestBuffer,
                                                             P2VAR(uint16, AUTOMATIC, RTE_APPL_DATA) BufSize);
FUNC(Std_ReturnType, Dem_CODE) Dem_GetEventFreezeFrameDataEx_GeneralEvtInfo(VAR(Dem_EventIdType, AUTOMATIC) EventId,
                                                                            VAR(uint8, AUTOMATIC) RecordNumber,
                                                                            VAR(uint16, AUTOMATIC) DataId,
                                                                            P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) DestBuffer,
                                                                            P2VAR(uint16, AUTOMATIC, RTE_APPL_DATA) BufSize);
FUNC(Std_ReturnType, Dem_CODE) Dem_GetEventFreezeFrameDataForRTE(VAR(Dem_EventIdType, AUTOMATIC) Rte_PDAV0,
                                                                 VAR(uint8, AUTOMATIC) RecordNumber,
                                                                 VAR(boolean, AUTOMATIC) ReportTotalRecord,
                                                                 VAR(uint16, AUTOMATIC) DataId,
                                                                 P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) DestBuffer);
FUNC(Std_ReturnType, Dem_CODE) Dem_GetEventFreezeFrameData_GeneralEvtInfo(VAR(Dem_EventIdType, AUTOMATIC) EventId,
                                                                          VAR(uint8, AUTOMATIC) RecordNumber,
                                                                          VAR(boolean, AUTOMATIC) ReportTotalRecord,
                                                                          VAR(uint16, AUTOMATIC) DataId,
                                                                          P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) DestBuffer);
FUNC(Std_ReturnType, Dem_CODE) Dem_GetEventMemoryOverflow(VAR(Dem_DTCOriginType, AUTOMATIC) Rte_PDAV0,
                                                          P2VAR(boolean, AUTOMATIC, RTE_APPL_DATA) OverflowIndication);
FUNC(Std_ReturnType, Dem_CODE) Dem_GetEventStatus(VAR(Dem_EventIdType, AUTOMATIC) Rte_PDAV0,
                                                  P2VAR(Dem_UdsStatusByteType, AUTOMATIC, RTE_APPL_DATA) EventStatusByte);
FUNC(Std_ReturnType, Dem_CODE) Dem_GetEventStatus_GeneralEvtInfo(VAR(Dem_EventIdType, AUTOMATIC) EventId,
                                                                 P2VAR(Dem_UdsStatusByteType, AUTOMATIC, RTE_APPL_DATA) EventStatusByte);
FUNC(Std_ReturnType, Dem_CODE) Dem_GetEventTested(VAR(Dem_EventIdType, AUTOMATIC) Rte_PDAV0,
                                                  P2VAR(boolean, AUTOMATIC, RTE_APPL_DATA) EventTested);
FUNC(Std_ReturnType, Dem_CODE) Dem_GetEventTested_GeneralEvtInfo(VAR(Dem_EventIdType, AUTOMATIC) EventId,
                                                                 P2VAR(boolean, AUTOMATIC, RTE_APPL_DATA) EventTested);
FUNC(Std_ReturnType, Dem_CODE) Dem_GetFaultDetectionCounter(VAR(Dem_EventIdType, AUTOMATIC) Rte_PDAV0,
                                                            P2VAR(sint8, AUTOMATIC, RTE_APPL_DATA) FaultDetectionCounter);
FUNC(Std_ReturnType, Dem_CODE) Dem_GetFaultDetectionCounter_GeneralEvtInfo(VAR(Dem_EventIdType, AUTOMATIC) EventId,
                                                                           P2VAR(sint8, AUTOMATIC, RTE_APPL_DATA) FaultDetectionCounter);
FUNC(Std_ReturnType, Dem_CODE) Dem_GetIndicatorStatus(VAR(uint8, AUTOMATIC) Rte_PDAV0,
                                                      P2VAR(Dem_IndicatorStatusType, AUTOMATIC, RTE_APPL_DATA) IndicatorStatus);
FUNC(Std_ReturnType, Dem_CODE) Dem_GetNumberOfEventMemoryEntries(VAR(Dem_DTCOriginType, AUTOMATIC) Rte_PDAV0,
                                                                 P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) NumberOfEventMemoryEntries);
FUNC(Std_ReturnType, Dem_CODE) Dem_GetOperationCycleState(VAR(Dem_OperationCycleIdType, AUTOMATIC) Rte_PDAV0,
                                                          P2VAR(Dem_OperationCycleStateType, AUTOMATIC, RTE_APPL_DATA) CycleState);
FUNC(Std_ReturnType, Dem_CODE) Dem_GetStorageCondition(VAR(uint8, AUTOMATIC) Rte_PDAV0,
                                                       P2VAR(boolean, AUTOMATIC, RTE_APPL_DATA) ConditionFulfilled);
FUNC(Std_ReturnType, Dem_CODE) Dem_PrestoreFreezeFrame(VAR(Dem_EventIdType, AUTOMATIC) Rte_PDAV0);
FUNC(Std_ReturnType, Dem_CODE) Dem_ResetEventDebounceStatus(VAR(Dem_EventIdType, AUTOMATIC) Rte_PDAV0,
                                                            VAR(Dem_DebounceResetStatusType, AUTOMATIC) DebounceResetStatus);
FUNC(Std_ReturnType, Dem_CODE) Dem_ResetEventStatus(VAR(Dem_EventIdType, AUTOMATIC) Rte_PDAV0);
FUNC(Std_ReturnType, Dem_CODE) Dem_SetCycleQualified(VAR(Dem_OperationCycleIdType, AUTOMATIC) Rte_PDAV0);
FUNC(Std_ReturnType, Dem_CODE) Dem_SetDTCSuppression(VAR(uint32, AUTOMATIC) DTC,
                                                     VAR(Dem_DTCFormatType, AUTOMATIC) DTCFormat,
                                                     VAR(boolean, AUTOMATIC) SuppressionStatus);
FUNC(Std_ReturnType, Dem_CODE) Dem_SetEnableCondition(VAR(uint8, AUTOMATIC) Rte_PDAV0,
                                                      VAR(boolean, AUTOMATIC) ConditionFulfilled);
FUNC(Std_ReturnType, Dem_CODE) Dem_SetEventAvailable(VAR(Dem_EventIdType, AUTOMATIC) Rte_PDAV0,
                                                     VAR(boolean, AUTOMATIC) AvailableStatus);
FUNC(Std_ReturnType, Dem_CODE) Dem_SetEventStatus(VAR(Dem_EventIdType, AUTOMATIC) Rte_PDAV0,
                                                  VAR(Dem_EventStatusType, AUTOMATIC) EventStatus);
FUNC(Std_ReturnType, Dem_CODE) Dem_SetOperationCycleState(VAR(Dem_OperationCycleIdType, AUTOMATIC) Rte_PDAV0,
                                                          VAR(Dem_OperationCycleStateType, AUTOMATIC) CycleState);
FUNC(Std_ReturnType, Dem_CODE) Dem_SetStorageCondition(VAR(uint8, AUTOMATIC) Rte_PDAV0,
                                                       VAR(boolean, AUTOMATIC) ConditionFulfilled);
FUNC(Std_ReturnType, Dem_CODE) Dem_SetWIRStatus(VAR(Dem_EventIdType, AUTOMATIC) Rte_PDAV0,
                                                VAR(boolean, AUTOMATIC) WIRStatus);
#define Dem_STOP_SEC_CODE
#include "Dem_MemMap.h" /*lint !e537 permit multiple inclusion */

/* Initial values for data element prototypes */

#ifdef __cplusplus
} /* extern C */
#endif /* __cplusplus */

#endif /* !RTE_DEM_H */
