/** @file     Rte_DataHandleType.h
  *
  * @brief    RTE DataElement type definitions
  *
  * @note     AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
  *
  * @note     Generated by ETAS RTA-RTE
  * @note     Version 6.4.0 
  *
  * @date     Sun Jul 29 21:33:08 2018
  */

#ifndef RTE_DATA_HANDLE_TYPE_H
#define RTE_DATA_HANDLE_TYPE_H

#include "Rte_Type.h"
#include "Rte_Cfg.h"

/* No DataElement types */


#endif /* !RTE_DATA_HANDLE_TYPE_H */
