/**********************************************************************************************************************
 *
 * COPYRIGHT RESERVED, Robert Bosch GmbH, 2014. All rights reserved.
 * The reproduction, distribution and utilization of this document as well as the communication of its contents to
 * others without explicit authorization is prohibited. Offenders will be held liable for the payment of damages.
 * All rights reserved in the event of the grant of a patent, utility model or design.
 *
 **********************************************************************************************************************/


/* MISRA RULE 19.15 VIOLATION: MemMap header concept - no protection against repeated inclusion intended */
#define BSW_MEMMAP_ERROR

//*****************************************************************************
// <MODULE>_START_SEC_VAR_<INIT_POLICY>_<SIZE>
// <MODULE>_STOP_SEC_VAR_<INIT_POLICY>_<SIZE>
//*****************************************************************************
#if defined BSW_START_SEC_VAR_NO_INIT_BOOLEAN
    #undef BSW_START_SEC_VAR_NO_INIT_BOOLEAN
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_VAR_NO_INIT_BOOLEAN
    #undef BSW_STOP_SEC_VAR_NO_INIT_BOOLEAN
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_VAR_NO_INIT_8
    #undef BSW_START_SEC_VAR_NO_INIT_8
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_VAR_NO_INIT_8
    #undef BSW_STOP_SEC_VAR_NO_INIT_8
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_VAR_NO_INIT_16
    #undef BSW_START_SEC_VAR_NO_INIT_16
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_VAR_NO_INIT_16
    #undef BSW_STOP_SEC_VAR_NO_INIT_16
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_VAR_NO_INIT_32
    #undef BSW_START_SEC_VAR_NO_INIT_32
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_VAR_NO_INIT_32
    #undef BSW_STOP_SEC_VAR_NO_INIT_32
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_VAR_NO_INIT_UNSPECIFIED
    #undef BSW_START_SEC_VAR_NO_INIT_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_VAR_NO_INIT_UNSPECIFIED
    #undef BSW_STOP_SEC_VAR_NO_INIT_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR

#elif defined BSW_START_SEC_VAR_CLEARED_BOOLEAN
    #undef BSW_START_SEC_VAR_CLEARED_BOOLEAN
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_VAR_CLEARED_BOOLEAN
    #undef BSW_STOP_SEC_VAR_CLEARED_BOOLEAN
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_VAR_CLEARED_8
    #undef BSW_START_SEC_VAR_CLEARED_8
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_VAR_CLEARED_8
    #undef BSW_STOP_SEC_VAR_CLEARED_8
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_VAR_CLEARED_16
    #undef BSW_START_SEC_VAR_CLEARED_16
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_VAR_CLEARED_16
    #undef BSW_STOP_SEC_VAR_CLEARED_16
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_VAR_CLEARED_32
    #undef BSW_START_SEC_VAR_CLEARED_32
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_VAR_CLEARED_32
    #undef BSW_STOP_SEC_VAR_CLEARED_32
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_VAR_CLEARED_UNSPECIFIED
    #undef BSW_START_SEC_VAR_CLEARED_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_VAR_CLEARED_UNSPECIFIED
    #undef BSW_STOP_SEC_VAR_CLEARED_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR

#elif defined BSW_START_SEC_VAR_POWER_ON_CLEARED_BOOLEAN
    #undef BSW_START_SEC_VAR_POWER_ON_CLEARED_BOOLEAN
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_VAR_POWER_ON_CLEARED_BOOLEAN
    #undef BSW_STOP_SEC_VAR_POWER_ON_CLEARED_BOOLEAN
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_VAR_POWER_ON_CLEARED_8
    #undef BSW_START_SEC_VAR_POWER_ON_CLEARED_8
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_VAR_POWER_ON_CLEARED_8
    #undef BSW_STOP_SEC_VAR_POWER_ON_CLEARED_8
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_VAR_POWER_ON_CLEARED_16
    #undef BSW_START_SEC_VAR_POWER_ON_CLEARED_16
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_VAR_POWER_ON_CLEARED_16
    #undef BSW_STOP_SEC_VAR_POWER_ON_CLEARED_16
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_VAR_POWER_ON_CLEARED_32
    #undef BSW_START_SEC_VAR_POWER_ON_CLEARED_32
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_VAR_POWER_ON_CLEARED_32
    #undef BSW_STOP_SEC_VAR_POWER_ON_CLEARED_32
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_VAR_POWER_ON_CLEARED_UNSPECIFIED
    #undef BSW_START_SEC_VAR_POWER_ON_CLEARED_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_VAR_POWER_ON_CLEARED_UNSPECIFIED
    #undef BSW_STOP_SEC_VAR_POWER_ON_CLEARED_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR

#elif defined BSW_START_SEC_VAR_INIT_BOOLEAN
    #undef BSW_START_SEC_VAR_INIT_BOOLEAN
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_VAR_INIT_BOOLEAN
    #undef BSW_STOP_SEC_VAR_INIT_BOOLEAN
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_VAR_INIT_8
    #undef BSW_START_SEC_VAR_INIT_8
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_VAR_INIT_8
    #undef BSW_STOP_SEC_VAR_INIT_8
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_VAR_INIT_16
    #undef BSW_START_SEC_VAR_INIT_16
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_VAR_INIT_16
    #undef BSW_STOP_SEC_VAR_INIT_16
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_VAR_INIT_32
    #undef BSW_START_SEC_VAR_INIT_32
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_VAR_INIT_32
    #undef BSW_STOP_SEC_VAR_INIT_32
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_VAR_INIT_UNSPECIFIED
    #undef BSW_START_SEC_VAR_INIT_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_VAR_INIT_UNSPECIFIED
    #undef BSW_STOP_SEC_VAR_INIT_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR

#elif defined BSW_START_SEC_VAR_POWER_ON_INIT_BOOLEAN
    #undef BSW_START_SEC_VAR_POWER_ON_INIT_BOOLEAN
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_VAR_POWER_ON_INIT_BOOLEAN
    #undef BSW_STOP_SEC_VAR_POWER_ON_INIT_BOOLEAN
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_VAR_POWER_ON_INIT_8
    #undef BSW_START_SEC_VAR_POWER_ON_INIT_8
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_VAR_POWER_ON_INIT_8
    #undef BSW_STOP_SEC_VAR_POWER_ON_INIT_8
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_VAR_POWER_ON_INIT_16
    #undef BSW_START_SEC_VAR_POWER_ON_INIT_16
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_VAR_POWER_ON_INIT_16
    #undef BSW_STOP_SEC_VAR_POWER_ON_INIT_16
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_VAR_POWER_ON_INIT_32
    #undef BSW_START_SEC_VAR_POWER_ON_INIT_32
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_VAR_POWER_ON_INIT_32
    #undef BSW_STOP_SEC_VAR_POWER_ON_INIT_32
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_VAR_POWER_ON_INIT_UNSPECIFIED
    #undef BSW_START_SEC_VAR_POWER_ON_INIT_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_VAR_POWER_ON_INIT_UNSPECIFIED
    #undef BSW_STOP_SEC_VAR_POWER_ON_INIT_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR
//*****************************************************************************

//*****************************************************************************
// <MODULE>_START_SEC_VAR_FAST_<INIT_POLICY>_<SIZE>
// <MODULE>_STOP_SEC_VAR_FAST_<INIT_POLICY>_<SIZE>
//*****************************************************************************
#elif defined BSW_START_SEC_VAR_FAST_NO_INIT_BOOLEAN
    #undef BSW_START_SEC_VAR_FAST_NO_INIT_BOOLEAN
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_VAR_FAST_NO_INIT_BOOLEAN
    #undef BSW_STOP_SEC_VAR_FAST_NO_INIT_BOOLEAN
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_VAR_FAST_NO_INIT_8
    #undef BSW_START_SEC_VAR_FAST_NO_INIT_8
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_VAR_FAST_NO_INIT_8
    #undef BSW_STOP_SEC_VAR_FAST_NO_INIT_8
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_VAR_FAST_NO_INIT_16
    #undef BSW_START_SEC_VAR_FAST_NO_INIT_16
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_VAR_FAST_NO_INIT_16
    #undef BSW_STOP_SEC_VAR_FAST_NO_INIT_16
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_VAR_FAST_NO_INIT_32
    #undef BSW_START_SEC_VAR_FAST_NO_INIT_32
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_VAR_FAST_NO_INIT_32
    #undef BSW_STOP_SEC_VAR_FAST_NO_INIT_32
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_VAR_FAST_NO_INIT_UNSPECIFIED
    #undef BSW_START_SEC_VAR_FAST_NO_INIT_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_VAR_FAST_NO_INIT_UNSPECIFIED
    #undef BSW_STOP_SEC_VAR_FAST_NO_INIT_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR

#elif defined BSW_START_SEC_VAR_FAST_CLEARED_BOOLEAN
    #undef BSW_START_SEC_VAR_FAST_CLEARED_BOOLEAN
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_VAR_FAST_CLEARED_BOOLEAN
    #undef BSW_STOP_SEC_VAR_FAST_CLEARED_BOOLEAN
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_VAR_FAST_CLEARED_8
    #undef BSW_START_SEC_VAR_FAST_CLEARED_8
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_VAR_FAST_CLEARED_8
    #undef BSW_STOP_SEC_VAR_FAST_CLEARED_8
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_VAR_FAST_CLEARED_16
    #undef BSW_START_SEC_VAR_FAST_CLEARED_16
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_VAR_FAST_CLEARED_16
    #undef BSW_STOP_SEC_VAR_FAST_CLEARED_16
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_VAR_FAST_CLEARED_32
    #undef BSW_START_SEC_VAR_FAST_CLEARED_32
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_VAR_FAST_CLEARED_32
    #undef BSW_STOP_SEC_VAR_FAST_CLEARED_32
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_VAR_FAST_CLEARED_UNSPECIFIED
    #undef BSW_START_SEC_VAR_FAST_CLEARED_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_VAR_FAST_CLEARED_UNSPECIFIED
    #undef BSW_STOP_SEC_VAR_FAST_CLEARED_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR

#elif defined BSW_START_SEC_VAR_FAST_POWER_ON_CLEARED_BOOLEAN
    #undef BSW_START_SEC_VAR_FAST_POWER_ON_CLEARED_BOOLEAN
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_BOOLEAN
    #undef BSW_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_BOOLEAN
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_VAR_FAST_POWER_ON_CLEARED_8
    #undef BSW_START_SEC_VAR_FAST_POWER_ON_CLEARED_8
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_8
    #undef BSW_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_8
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_VAR_FAST_POWER_ON_CLEARED_16
    #undef BSW_START_SEC_VAR_FAST_POWER_ON_CLEARED_16
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_16
    #undef BSW_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_16
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_VAR_FAST_POWER_ON_CLEARED_32
    #undef BSW_START_SEC_VAR_FAST_POWER_ON_CLEARED_32
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_32
    #undef BSW_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_32
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_VAR_FAST_POWER_ON_CLEARED_UNSPECIFIED
    #undef BSW_START_SEC_VAR_FAST_POWER_ON_CLEARED_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_UNSPECIFIED
    #undef BSW_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR

#elif defined BSW_START_SEC_VAR_FAST_INIT_BOOLEAN
    #undef BSW_START_SEC_VAR_FAST_INIT_BOOLEAN
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_VAR_FAST_INIT_BOOLEAN
    #undef BSW_STOP_SEC_VAR_FAST_INIT_BOOLEAN
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_VAR_FAST_INIT_8
    #undef BSW_START_SEC_VAR_FAST_INIT_8
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_VAR_FAST_INIT_8
    #undef BSW_STOP_SEC_VAR_FAST_INIT_8
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_VAR_FAST_INIT_16
    #undef BSW_START_SEC_VAR_FAST_INIT_16
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_VAR_FAST_INIT_16
    #undef BSW_STOP_SEC_VAR_FAST_INIT_16
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_VAR_FAST_INIT_32
    #undef BSW_START_SEC_VAR_FAST_INIT_32
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_VAR_FAST_INIT_32
    #undef BSW_STOP_SEC_VAR_FAST_INIT_32
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_VAR_FAST_INIT_UNSPECIFIED
    #undef BSW_START_SEC_VAR_FAST_INIT_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_VAR_FAST_INIT_UNSPECIFIED
    #undef BSW_STOP_SEC_VAR_FAST_INIT_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR

#elif defined BSW_START_SEC_VAR_FAST_POWER_ON_INIT_BOOLEAN
    #undef BSW_START_SEC_VAR_FAST_POWER_ON_INIT_BOOLEAN
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_VAR_FAST_POWER_ON_INIT_BOOLEAN
    #undef BSW_STOP_SEC_VAR_FAST_POWER_ON_INIT_BOOLEAN
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_VAR_FAST_POWER_ON_INIT_8
    #undef BSW_START_SEC_VAR_FAST_POWER_ON_INIT_8
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_VAR_FAST_POWER_ON_INIT_8
    #undef BSW_STOP_SEC_VAR_FAST_POWER_ON_INIT_8
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_VAR_FAST_POWER_ON_INIT_16
    #undef BSW_START_SEC_VAR_FAST_POWER_ON_INIT_16
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_VAR_FAST_POWER_ON_INIT_16
    #undef BSW_STOP_SEC_VAR_FAST_POWER_ON_INIT_16
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_VAR_FAST_POWER_ON_INIT_32
    #undef BSW_START_SEC_VAR_FAST_POWER_ON_INIT_32
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_VAR_FAST_POWER_ON_INIT_32
    #undef BSW_STOP_SEC_VAR_FAST_POWER_ON_INIT_32
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_VAR_FAST_POWER_ON_INIT_UNSPECIFIED
    #undef BSW_START_SEC_VAR_FAST_POWER_ON_INIT_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_VAR_FAST_POWER_ON_INIT_UNSPECIFIED
    #undef BSW_STOP_SEC_VAR_FAST_POWER_ON_INIT_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR
//*****************************************************************************

//*****************************************************************************
// <MODULE>_START_SEC_VAR_SLOW_<INIT_POLICY>_<SIZE>
// <MODULE>_STOP_SEC_VAR_SLOW_<INIT_POLICY>_<SIZE>
//*****************************************************************************
#elif defined BSW_START_SEC_VAR_SLOW_NO_INIT_BOOLEAN
    #undef BSW_START_SEC_VAR_SLOW_NO_INIT_BOOLEAN
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_VAR_SLOW_NO_INIT_BOOLEAN
    #undef BSW_STOP_SEC_VAR_SLOW_NO_INIT_BOOLEAN
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_VAR_SLOW_NO_INIT_8
    #undef BSW_START_SEC_VAR_SLOW_NO_INIT_8
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_VAR_SLOW_NO_INIT_8
    #undef BSW_STOP_SEC_VAR_SLOW_NO_INIT_8
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_VAR_SLOW_NO_INIT_16
    #undef BSW_START_SEC_VAR_SLOW_NO_INIT_16
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_VAR_SLOW_NO_INIT_16
    #undef BSW_STOP_SEC_VAR_SLOW_NO_INIT_16
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_VAR_SLOW_NO_INIT_32
    #undef BSW_START_SEC_VAR_SLOW_NO_INIT_32
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_VAR_SLOW_NO_INIT_32
    #undef BSW_STOP_SEC_VAR_SLOW_NO_INIT_32
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_VAR_SLOW_NO_INIT_UNSPECIFIED
    #undef BSW_START_SEC_VAR_SLOW_NO_INIT_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_VAR_SLOW_NO_INIT_UNSPECIFIED
    #undef BSW_STOP_SEC_VAR_SLOW_NO_INIT_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR

#elif defined BSW_START_SEC_VAR_SLOW_CLEARED_BOOLEAN
    #undef BSW_START_SEC_VAR_SLOW_CLEARED_BOOLEAN
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_VAR_SLOW_CLEARED_BOOLEAN
    #undef BSW_STOP_SEC_VAR_SLOW_CLEARED_BOOLEAN
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_VAR_SLOW_CLEARED_8
    #undef BSW_START_SEC_VAR_SLOW_CLEARED_8
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_VAR_SLOW_CLEARED_8
    #undef BSW_STOP_SEC_VAR_SLOW_CLEARED_8
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_VAR_SLOW_CLEARED_16
    #undef BSW_START_SEC_VAR_SLOW_CLEARED_16
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_VAR_SLOW_CLEARED_16
    #undef BSW_STOP_SEC_VAR_SLOW_CLEARED_16
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_VAR_SLOW_CLEARED_32
    #undef BSW_START_SEC_VAR_SLOW_CLEARED_32
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_VAR_SLOW_CLEARED_32
    #undef BSW_STOP_SEC_VAR_SLOW_CLEARED_32
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_VAR_SLOW_CLEARED_UNSPECIFIED
    #undef BSW_START_SEC_VAR_SLOW_CLEARED_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_VAR_SLOW_CLEARED_UNSPECIFIED
    #undef BSW_STOP_SEC_VAR_SLOW_CLEARED_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR

#elif defined BSW_START_SEC_VAR_SLOW_POWER_ON_CLEARED_BOOLEAN
    #undef BSW_START_SEC_VAR_SLOW_POWER_ON_CLEARED_BOOLEAN
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_BOOLEAN
    #undef BSW_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_BOOLEAN
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_VAR_SLOW_POWER_ON_CLEARED_8
    #undef BSW_START_SEC_VAR_SLOW_POWER_ON_CLEARED_8
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_8
    #undef BSW_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_8
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_VAR_SLOW_POWER_ON_CLEARED_16
    #undef BSW_START_SEC_VAR_SLOW_POWER_ON_CLEARED_16
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_16
    #undef BSW_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_16
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_VAR_SLOW_POWER_ON_CLEARED_32
    #undef BSW_START_SEC_VAR_SLOW_POWER_ON_CLEARED_32
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_32
    #undef BSW_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_32
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_VAR_SLOW_POWER_ON_CLEARED_UNSPECIFIED
    #undef BSW_START_SEC_VAR_SLOW_POWER_ON_CLEARED_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_UNSPECIFIED
    #undef BSW_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR

#elif defined BSW_START_SEC_VAR_SLOW_INIT_BOOLEAN
    #undef BSW_START_SEC_VAR_SLOW_INIT_BOOLEAN
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_VAR_SLOW_INIT_BOOLEAN
    #undef BSW_STOP_SEC_VAR_SLOW_INIT_BOOLEAN
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_VAR_SLOW_INIT_8
    #undef BSW_START_SEC_VAR_SLOW_INIT_8
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_VAR_SLOW_INIT_8
    #undef BSW_STOP_SEC_VAR_SLOW_INIT_8
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_VAR_SLOW_INIT_16
    #undef BSW_START_SEC_VAR_SLOW_INIT_16
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_VAR_SLOW_INIT_16
    #undef BSW_STOP_SEC_VAR_SLOW_INIT_16
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_VAR_SLOW_INIT_32
    #undef BSW_START_SEC_VAR_SLOW_INIT_32
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_VAR_SLOW_INIT_32
    #undef BSW_STOP_SEC_VAR_SLOW_INIT_32
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_VAR_SLOW_INIT_UNSPECIFIED
    #undef BSW_START_SEC_VAR_SLOW_INIT_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_VAR_SLOW_INIT_UNSPECIFIED
    #undef BSW_STOP_SEC_VAR_SLOW_INIT_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR

#elif defined BSW_START_SEC_VAR_SLOW_POWER_ON_INIT_BOOLEAN
    #undef BSW_START_SEC_VAR_SLOW_POWER_ON_INIT_BOOLEAN
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_VAR_SLOW_POWER_ON_INIT_BOOLEAN
    #undef BSW_STOP_SEC_VAR_SLOW_POWER_ON_INIT_BOOLEAN
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_VAR_SLOW_POWER_ON_INIT_8
    #undef BSW_START_SEC_VAR_SLOW_POWER_ON_INIT_8
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_VAR_SLOW_POWER_ON_INIT_8
    #undef BSW_STOP_SEC_VAR_SLOW_POWER_ON_INIT_8
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_VAR_SLOW_POWER_ON_INIT_16
    #undef BSW_START_SEC_VAR_SLOW_POWER_ON_INIT_16
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_VAR_SLOW_POWER_ON_INIT_16
    #undef BSW_STOP_SEC_VAR_SLOW_POWER_ON_INIT_16
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_VAR_SLOW_POWER_ON_INIT_32
    #undef BSW_START_SEC_VAR_SLOW_POWER_ON_INIT_32
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_VAR_SLOW_POWER_ON_INIT_32
    #undef BSW_STOP_SEC_VAR_SLOW_POWER_ON_INIT_32
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_VAR_SLOW_POWER_ON_INIT_UNSPECIFIED
    #undef BSW_START_SEC_VAR_SLOW_POWER_ON_INIT_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_VAR_SLOW_POWER_ON_INIT_UNSPECIFIED
    #undef BSW_STOP_SEC_VAR_SLOW_POWER_ON_INIT_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR
//*****************************************************************************

//*****************************************************************************
// <MODULE>_START_SEC_INTERNAL_VAR_<INIT_POLICY>_<SIZE>
// <MODULE>_START_SEC_INTERNAL_VAR_<INIT_POLICY>_<SIZE>
//*****************************************************************************
#elif defined BSW_START_SEC_INTERNAL_VAR_NO_INIT_BOOLEAN
    #undef BSW_START_SEC_INTERNAL_VAR_NO_INIT_BOOLEAN
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_INTERNAL_VAR_NO_INIT_BOOLEAN
    #undef BSW_STOP_SEC_INTERNAL_VAR_NO_INIT_BOOLEAN
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_INTERNAL_VAR_NO_INIT_8
    #undef BSW_START_SEC_INTERNAL_VAR_NO_INIT_8
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_INTERNAL_VAR_NO_INIT_8
    #undef BSW_STOP_SEC_INTERNAL_VAR_NO_INIT_8
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_INTERNAL_VAR_NO_INIT_16
    #undef BSW_START_SEC_INTERNAL_VAR_NO_INIT_16
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_INTERNAL_VAR_NO_INIT_16
    #undef BSW_STOP_SEC_INTERNAL_VAR_NO_INIT_16
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_INTERNAL_VAR_NO_INIT_32
    #undef BSW_START_SEC_INTERNAL_VAR_NO_INIT_32
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_INTERNAL_VAR_NO_INIT_32
    #undef BSW_STOP_SEC_INTERNAL_VAR_NO_INIT_32
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_INTERNAL_VAR_NO_INIT_UNSPECIFIED
    #undef BSW_START_SEC_INTERNAL_VAR_NO_INIT_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_INTERNAL_VAR_NO_INIT_UNSPECIFIED
    #undef BSW_STOP_SEC_INTERNAL_VAR_NO_INIT_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR

#elif defined BSW_START_SEC_INTERNAL_VAR_CLEARED_BOOLEAN
    #undef BSW_START_SEC_INTERNAL_VAR_CLEARED_BOOLEAN
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_INTERNAL_VAR_CLEARED_BOOLEAN
    #undef BSW_STOP_SEC_INTERNAL_VAR_CLEARED_BOOLEAN
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_INTERNAL_VAR_CLEARED_8
    #undef BSW_START_SEC_INTERNAL_VAR_CLEARED_8
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_INTERNAL_VAR_CLEARED_8
    #undef BSW_STOP_SEC_INTERNAL_VAR_CLEARED_8
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_INTERNAL_VAR_CLEARED_16
    #undef BSW_START_SEC_INTERNAL_VAR_CLEARED_16
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_INTERNAL_VAR_CLEARED_16
    #undef BSW_STOP_SEC_INTERNAL_VAR_CLEARED_16
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_INTERNAL_VAR_CLEARED_32
    #undef BSW_START_SEC_INTERNAL_VAR_CLEARED_32
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_INTERNAL_VAR_CLEARED_32
    #undef BSW_STOP_SEC_INTERNAL_VAR_CLEARED_32
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_INTERNAL_VAR_CLEARED_UNSPECIFIED
    #undef BSW_START_SEC_INTERNAL_VAR_CLEARED_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_INTERNAL_VAR_CLEARED_UNSPECIFIED
    #undef BSW_STOP_SEC_INTERNAL_VAR_CLEARED_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR

#elif defined BSW_START_SEC_INTERNAL_VAR_POWER_ON_CLEARED_BOOLEAN
    #undef BSW_START_SEC_INTERNAL_VAR_POWER_ON_CLEARED_BOOLEAN
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_INTERNAL_VAR_POWER_ON_CLEARED_BOOLEAN
    #undef BSW_STOP_SEC_INTERNAL_VAR_POWER_ON_CLEARED_BOOLEAN
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_INTERNAL_VAR_POWER_ON_CLEARED_8
    #undef BSW_START_SEC_INTERNAL_VAR_POWER_ON_CLEARED_8
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_INTERNAL_VAR_POWER_ON_CLEARED_8
    #undef BSW_STOP_SEC_INTERNAL_VAR_POWER_ON_CLEARED_8
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_INTERNAL_VAR_POWER_ON_CLEARED_16
    #undef BSW_START_SEC_INTERNAL_VAR_POWER_ON_CLEARED_16
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_INTERNAL_VAR_POWER_ON_CLEARED_16
    #undef BSW_STOP_SEC_INTERNAL_VAR_POWER_ON_CLEARED_16
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_INTERNAL_VAR_POWER_ON_CLEARED_32
    #undef BSW_START_SEC_INTERNAL_VAR_POWER_ON_CLEARED_32
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_INTERNAL_VAR_POWER_ON_CLEARED_32
    #undef BSW_STOP_SEC_INTERNAL_VAR_POWER_ON_CLEARED_32
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_INTERNAL_VAR_POWER_ON_CLEARED_UNSPECIFIED
    #undef BSW_START_SEC_INTERNAL_VAR_POWER_ON_CLEARED_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_INTERNAL_VAR_POWER_ON_CLEARED_UNSPECIFIED
    #undef BSW_STOP_SEC_INTERNAL_VAR_POWER_ON_CLEARED_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR

#elif defined BSW_START_SEC_INTERNAL_VAR_INIT_BOOLEAN
    #undef BSW_START_SEC_INTERNAL_VAR_INIT_BOOLEAN
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_INTERNAL_VAR_INIT_BOOLEAN
    #undef BSW_STOP_SEC_INTERNAL_VAR_INIT_BOOLEAN
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_INTERNAL_VAR_INIT_8
    #undef BSW_START_SEC_INTERNAL_VAR_INIT_8
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_INTERNAL_VAR_INIT_8
    #undef BSW_STOP_SEC_INTERNAL_VAR_INIT_8
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_INTERNAL_VAR_INIT_16
    #undef BSW_START_SEC_INTERNAL_VAR_INIT_16
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_INTERNAL_VAR_INIT_16
    #undef BSW_STOP_SEC_INTERNAL_VAR_INIT_16
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_INTERNAL_VAR_INIT_32
    #undef BSW_START_SEC_INTERNAL_VAR_INIT_32
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_INTERNAL_VAR_INIT_32
    #undef BSW_STOP_SEC_INTERNAL_VAR_INIT_32
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_INTERNAL_VAR_INIT_UNSPECIFIED
    #undef BSW_START_SEC_INTERNAL_VAR_INIT_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_INTERNAL_VAR_INIT_UNSPECIFIED
    #undef BSW_STOP_SEC_INTERNAL_VAR_INIT_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR

#elif defined BSW_START_SEC_INTERNAL_VAR_POWER_ON_INIT_BOOLEAN
    #undef BSW_START_SEC_INTERNAL_VAR_POWER_ON_INIT_BOOLEAN
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_BOOLEAN
    #undef BSW_STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_BOOLEAN
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_INTERNAL_VAR_POWER_ON_INIT_8
    #undef BSW_START_SEC_INTERNAL_VAR_POWER_ON_INIT_8
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_8
    #undef BSW_STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_8
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_INTERNAL_VAR_POWER_ON_INIT_16
    #undef BSW_START_SEC_INTERNAL_VAR_POWER_ON_INIT_16
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_16
    #undef BSW_STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_16
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_INTERNAL_VAR_POWER_ON_INIT_32
    #undef BSW_START_SEC_INTERNAL_VAR_POWER_ON_INIT_32
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_32
    #undef BSW_STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_32
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_INTERNAL_VAR_POWER_ON_INIT_UNSPECIFIED
    #undef BSW_START_SEC_INTERNAL_VAR_POWER_ON_INIT_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_UNSPECIFIED
    #undef BSW_STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR
//*****************************************************************************

//*****************************************************************************
// <MODULE>_START_SEC_VAR_SAVED_ZONE<X>_<SIZE>
// <MODULE>_STOP_SEC_VAR_SAVED_ZONE<X>_<SIZE>
//*****************************************************************************
#elif defined BSW_START_SEC_VAR_SAVED_ZONE_BOOLEAN
    #undef BSW_START_SEC_VAR_SAVED_ZONE_BOOLEAN
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_VAR_SAVED_ZONE_BOOLEAN
    #undef BSW_STOP_SEC_VAR_SAVED_ZONE_BOOLEAN
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_VAR_SAVED_ZONE_8
    #undef BSW_START_SEC_VAR_SAVED_ZONE_8
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_VAR_SAVED_ZONE_8
    #undef BSW_STOP_SEC_VAR_SAVED_ZONE_8
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_VAR_SAVED_ZONE_16
    #undef BSW_START_SEC_VAR_SAVED_ZONE_16
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_VAR_SAVED_ZONE_16
    #undef BSW_STOP_SEC_VAR_SAVED_ZONE_16
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_VAR_SAVED_ZONE_32
    #undef BSW_START_SEC_VAR_SAVED_ZONE_32
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_VAR_SAVED_ZONE_32
    #undef BSW_STOP_SEC_VAR_SAVED_ZONE_32
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_VAR_SAVED_ZONE_UNSPECIFIED
    #undef BSW_START_SEC_VAR_SAVED_ZONE_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_VAR_SAVED_ZONE_UNSPECIFIED
    #undef BSW_STOP_SEC_VAR_SAVED_ZONE_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR
//*****************************************************************************

//*****************************************************************************
// <MODULE>_START_SEC_CONST_<SIZE>
// <MODULE>_STOP_SEC_CONST_<SIZE>
//*****************************************************************************
#elif defined BSW_START_SEC_CONST_BOOLEAN
    #undef BSW_START_SEC_CONST_BOOLEAN
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_CONST_BOOLEAN
    #undef BSW_STOP_SEC_CONST_BOOLEAN
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_CONST_8
    #undef BSW_START_SEC_CONST_8
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_CONST_8
    #undef BSW_STOP_SEC_CONST_8
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_CONST_16
    #undef BSW_START_SEC_CONST_16
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_CONST_16
    #undef BSW_STOP_SEC_CONST_16
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_CONST_32
    #undef BSW_START_SEC_CONST_32
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_CONST_32
    #undef BSW_STOP_SEC_CONST_32
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_CONST_UNSPECIFIED
    #undef BSW_START_SEC_CONST_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_CONST_UNSPECIFIED
    #undef BSW_STOP_SEC_CONST_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR
//*****************************************************************************

//*****************************************************************************
// <MODULE>_START_SEC_CONST_FAST_<SIZE>
// <MODULE>_STOP_SEC_CONST_FAST_<SIZE>
//*****************************************************************************
#elif defined BSW_START_SEC_CONST_FAST_BOOLEAN
    #undef BSW_START_SEC_CONST_FAST_BOOLEAN
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_CONST_FAST_BOOLEAN
    #undef BSW_STOP_SEC_CONST_FAST_BOOLEAN
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_CONST_FAST_8
    #undef BSW_START_SEC_CONST_FAST_8
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_CONST_FAST_8
    #undef BSW_STOP_SEC_CONST_FAST_8
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_CONST_FAST_16
    #undef BSW_START_SEC_CONST_FAST_16
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_CONST_FAST_16
    #undef BSW_STOP_SEC_CONST_FAST_16
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_CONST_FAST_32
    #undef BSW_START_SEC_CONST_FAST_32
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_CONST_FAST_32
    #undef BSW_STOP_SEC_CONST_FAST_32
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_CONST_FAST_UNSPECIFIED
    #undef BSW_START_SEC_CONST_FAST_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_CONST_FAST_UNSPECIFIED
    #undef BSW_STOP_SEC_CONST_FAST_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR
//*****************************************************************************

//*****************************************************************************
// <MODULE>_START_SEC_CONST_SLOW_<SIZE>
// <MODULE>_STOP_SEC_CONST_SLOW_<SIZE>
//*****************************************************************************
#elif defined BSW_START_SEC_CONST_SLOW_BOOLEAN
    #undef BSW_START_SEC_CONST_SLOW_BOOLEAN
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_CONST_SLOW_BOOLEAN
    #undef BSW_STOP_SEC_CONST_SLOW_BOOLEAN
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_CONST_SLOW_8
    #undef BSW_START_SEC_CONST_SLOW_8
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_CONST_SLOW_8
    #undef BSW_STOP_SEC_CONST_SLOW_8
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_CONST_SLOW_16
    #undef BSW_START_SEC_CONST_SLOW_16
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_CONST_SLOW_16
    #undef BSW_STOP_SEC_CONST_SLOW_16
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_CONST_SLOW_32
    #undef BSW_START_SEC_CONST_SLOW_32
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_CONST_SLOW_32
    #undef BSW_STOP_SEC_CONST_SLOW_32
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_CONST_SLOW_UNSPECIFIED
    #undef BSW_START_SEC_CONST_SLOW_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_CONST_SLOW_UNSPECIFIED
    #undef BSW_STOP_SEC_CONST_SLOW_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR
//*****************************************************************************

//*****************************************************************************
// <MODULE>_START_SEC_CALIB_<SIZE>
// <MODULE>_STOP_SEC_CALIB_<SIZE>
//*****************************************************************************
#elif defined BSW_START_SEC_CALIB_BOOLEAN
    #undef BSW_START_SEC_CALIB_BOOLEAN
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_CALIB_BOOLEAN
    #undef BSW_STOP_SEC_CALIB_BOOLEAN
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_CALIB_8
    #undef BSW_START_SEC_CALIB_8
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_CALIB_8
    #undef BSW_STOP_SEC_CALIB_8
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_CALIB_16
    #undef BSW_START_SEC_CALIB_16
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_CALIB_16
    #undef BSW_STOP_SEC_CALIB_16
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_CALIB_32
    #undef BSW_START_SEC_CALIB_32
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_CALIB_32
    #undef BSW_STOP_SEC_CALIB_32
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_CALIB_UNSPECIFIED
    #undef BSW_START_SEC_CALIB_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_CALIB_UNSPECIFIED
    #undef BSW_STOP_SEC_CALIB_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR
//*****************************************************************************

//*****************************************************************************
// <MODULE>_START_SEC_CALIB_FAST_<SIZE>
// <MODULE>_STOP_SEC_CALIB_FAST_<SIZE>
//*****************************************************************************
#elif defined BSW_START_SEC_CALIB_FAST_BOOLEAN
    #undef BSW_START_SEC_CALIB_FAST_BOOLEAN
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_CALIB_FAST_BOOLEAN
    #undef BSW_STOP_SEC_CALIB_FAST_BOOLEAN
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_CALIB_FAST_8
    #undef BSW_START_SEC_CALIB_FAST_8
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_CALIB_FAST_8
    #undef BSW_STOP_SEC_CALIB_FAST_8
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_CALIB_FAST_16
    #undef BSW_START_SEC_CALIB_FAST_16
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_CALIB_FAST_16
    #undef BSW_STOP_SEC_CALIB_FAST_16
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_CALIB_FAST_32
    #undef BSW_START_SEC_CALIB_FAST_32
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_CALIB_FAST_32
    #undef BSW_STOP_SEC_CALIB_FAST_32
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_CALIB_FAST_UNSPECIFIED
    #undef BSW_START_SEC_CALIB_FAST_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_CALIB_FAST_UNSPECIFIED
    #undef BSW_STOP_SEC_CALIB_FAST_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR
//*****************************************************************************

//*****************************************************************************
// <MODULE>_START_SEC_CALIB_SLOW_<SIZE>
// <MODULE>_STOP_SEC_CALIB_SLOW_<SIZE>
//*****************************************************************************
#elif defined BSW_START_SEC_CALIB_SLOW_BOOLEAN
    #undef BSW_START_SEC_CALIB_SLOW_BOOLEAN
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_CALIB_SLOW_BOOLEAN
    #undef BSW_STOP_SEC_CALIB_SLOW_BOOLEAN
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_CALIB_SLOW_8
    #undef BSW_START_SEC_CALIB_SLOW_8
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_CALIB_SLOW_8
    #undef BSW_STOP_SEC_CALIB_SLOW_8
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_CALIB_SLOW_16
    #undef BSW_START_SEC_CALIB_SLOW_16
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_CALIB_SLOW_16
    #undef BSW_STOP_SEC_CALIB_SLOW_16
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_CALIB_SLOW_32
    #undef BSW_START_SEC_CALIB_SLOW_32
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_CALIB_SLOW_32
    #undef BSW_STOP_SEC_CALIB_SLOW_32
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_CALIB_SLOW_UNSPECIFIED
    #undef BSW_START_SEC_CALIB_SLOW_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_CALIB_SLOW_UNSPECIFIED
    #undef BSW_STOP_SEC_CALIB_SLOW_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR
//*****************************************************************************

//*****************************************************************************
// <MODULE>_START_SEC_CARTO_<SIZE>
// <MODULE>_STOP_SEC_CARTO_<SIZE>
//*****************************************************************************
#elif defined BSW_START_SEC_CARTO_SLOW_BOOLEAN
    #undef BSW_START_SEC_CARTO_SLOW_BOOLEAN
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_CARTO_SLOW_BOOLEAN
    #undef BSW_STOP_SEC_CARTO_SLOW_BOOLEAN
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_CARTO_SLOW_8
    #undef BSW_START_SEC_CARTO_SLOW_8
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_CARTO_SLOW_8
    #undef BSW_STOP_SEC_CARTO_SLOW_8
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_CARTO_SLOW_16
    #undef BSW_START_SEC_CARTO_SLOW_16
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_CARTO_SLOW_16
    #undef BSW_STOP_SEC_CARTO_SLOW_16
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_CARTO_SLOW_32
    #undef BSW_START_SEC_CARTO_SLOW_32
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_CARTO_SLOW_32
    #undef BSW_STOP_SEC_CARTO_SLOW_32
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_CARTO_SLOW_UNSPECIFIED
    #undef BSW_START_SEC_CARTO_SLOW_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_CARTO_SLOW_UNSPECIFIED
    #undef BSW_STOP_SEC_CARTO_SLOW_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR
//*****************************************************************************

//*****************************************************************************
// <MODULE>_START_SEC_CONFIG_DATA_<SIZE>
// <MODULE>_STOP_SEC_CONFIG_DATA_<SIZE>
//*****************************************************************************
#elif defined BSW_START_SEC_CONFIG_DATA_BOOLEAN
    #undef BSW_START_SEC_CONFIG_DATA_BOOLEAN
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_CONFIG_DATA_BOOLEAN
    #undef BSW_STOP_SEC_CONFIG_DATA_BOOLEAN
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_CONFIG_DATA_8
    #undef BSW_START_SEC_CONFIG_DATA_8
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_CONFIG_DATA_8
    #undef BSW_STOP_SEC_CONFIG_DATA_8
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_CONFIG_DATA_16
    #undef BSW_START_SEC_CONFIG_DATA_16
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_CONFIG_DATA_16
    #undef BSW_STOP_SEC_CONFIG_DATA_16
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_CONFIG_DATA_32
    #undef BSW_START_SEC_CONFIG_DATA_32
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_CONFIG_DATA_32
    #undef BSW_STOP_SEC_CONFIG_DATA_32
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_CONFIG_DATA_UNSPECIFIED
    #undef BSW_START_SEC_CONFIG_DATA_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_CONFIG_DATA_UNSPECIFIED
    #undef BSW_STOP_SEC_CONFIG_DATA_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR
//*****************************************************************************

//*****************************************************************************
// <MODULE>_START_SEC_CONFIG_DATA_FAST_<SIZE>
// <MODULE>_STOP_SEC_CONFIG_DATA_FAST_<SIZE>
//*****************************************************************************
#elif defined BSW_START_SEC_CONFIG_DATA_FAST_BOOLEAN
    #undef BSW_START_SEC_CONFIG_DATA_FAST_BOOLEAN
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_CONFIG_DATA_FAST_BOOLEAN
    #undef BSW_STOP_SEC_CONFIG_DATA_FAST_BOOLEAN
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_CONFIG_DATA_FAST_8
    #undef BSW_START_SEC_CONFIG_DATA_FAST_8
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_CONFIG_DATA_FAST_8
    #undef BSW_STOP_SEC_CONFIG_DATA_FAST_8
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_CONFIG_DATA_FAST_16
    #undef BSW_START_SEC_CONFIG_DATA_FAST_16
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_CONFIG_DATA_FAST_16
    #undef BSW_STOP_SEC_CONFIG_DATA_FAST_16
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_CONFIG_DATA_FAST_32
    #undef BSW_START_SEC_CONFIG_DATA_FAST_32
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_CONFIG_DATA_FAST_32
    #undef BSW_STOP_SEC_CONFIG_DATA_FAST_32
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_CONFIG_DATA_FAST_UNSPECIFIED
    #undef BSW_START_SEC_CONFIG_DATA_FAST_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_CONFIG_DATA_FAST_UNSPECIFIED
    #undef BSW_STOP_SEC_CONFIG_DATA_FAST_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR
//*****************************************************************************

//*****************************************************************************
// <MODULE>_START_SEC_CONFIG_DATA_SLOW_<SIZE>
// <MODULE>_STOP_SEC_CONFIG_DATA_SLOW_<SIZE>
//*****************************************************************************
#elif defined BSW_START_SEC_CONFIG_DATA_SLOW_BOOLEAN
    #undef BSW_START_SEC_CONFIG_DATA_SLOW_BOOLEAN
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_CONFIG_DATA_SLOW_BOOLEAN
    #undef BSW_STOP_SEC_CONFIG_DATA_SLOW_BOOLEAN
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_CONFIG_DATA_SLOW_8
    #undef BSW_START_SEC_CONFIG_DATA_SLOW_8
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_CONFIG_DATA_SLOW_8
    #undef BSW_STOP_SEC_CONFIG_DATA_SLOW_8
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_CONFIG_DATA_SLOW_16
    #undef BSW_START_SEC_CONFIG_DATA_SLOW_16
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_CONFIG_DATA_SLOW_16
    #undef BSW_STOP_SEC_CONFIG_DATA_SLOW_16
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_CONFIG_DATA_SLOW_32
    #undef BSW_START_SEC_CONFIG_DATA_SLOW_32
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_CONFIG_DATA_SLOW_32
    #undef BSW_STOP_SEC_CONFIG_DATA_SLOW_32
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_CONFIG_DATA_SLOW_UNSPECIFIED
    #undef BSW_START_SEC_CONFIG_DATA_SLOW_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_CONFIG_DATA_SLOW_UNSPECIFIED
    #undef BSW_STOP_SEC_CONFIG_DATA_SLOW_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR
//*****************************************************************************

//*****************************************************************************
// <MODULE>_START_SEC_CONFIG_DATA_POSTBUILD_<SIZE>
// <MODULE>_STOP_SEC_CONFIG_DATA_POSTBUILD_<SIZE>
//*****************************************************************************
#elif defined BSW_START_SEC_CONFIG_DATA_POSTBUILD_BOOLEAN
    #undef BSW_START_SEC_CONFIG_DATA_POSTBUILD_BOOLEAN
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_CONFIG_DATA_POSTBUILD_BOOLEAN
    #undef BSW_STOP_SEC_CONFIG_DATA_POSTBUILD_BOOLEAN
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_CONFIG_DATA_POSTBUILD_8
    #undef BSW_START_SEC_CONFIG_DATA_POSTBUILD_8
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_CONFIG_DATA_POSTBUILD_8
    #undef BSW_STOP_SEC_CONFIG_DATA_POSTBUILD_8
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_CONFIG_DATA_POSTBUILD_16
    #undef BSW_START_SEC_CONFIG_DATA_POSTBUILD_16
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_CONFIG_DATA_POSTBUILD_16
    #undef BSW_STOP_SEC_CONFIG_DATA_POSTBUILD_16
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_CONFIG_DATA_POSTBUILD_32
    #undef BSW_START_SEC_CONFIG_DATA_POSTBUILD_32
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_CONFIG_DATA_POSTBUILD_32
    #undef BSW_STOP_SEC_CONFIG_DATA_POSTBUILD_32
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_CONFIG_DATA_POSTBUILD_UNSPECIFIED
    #undef BSW_START_SEC_CONFIG_DATA_POSTBUILD_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_CONFIG_DATA_POSTBUILD_UNSPECIFIED
    #undef BSW_STOP_SEC_CONFIG_DATA_POSTBUILD_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR
//*****************************************************************************

//*****************************************************************************
// <MODULE>_START_SEC_VAR_SAVED_RECOVERY_ZONE_<SIZE>
// <MODULE>_STOP_SEC_VAR_SAVED_RECOVERY_ZONE_<SIZE>
//*****************************************************************************
#elif defined BSW_START_SEC_VAR_SAVED_RECOVERY_ZONE_BOOLEAN
    #undef BSW_START_SEC_VAR_SAVED_RECOVERY_ZONE_BOOLEAN
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_VAR_SAVED_RECOVERY_ZONE_BOOLEAN
    #undef BSW_STOP_SEC_VAR_SAVED_RECOVERY_ZONE_BOOLEAN
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_VAR_SAVED_RECOVERY_ZONE_8
    #undef BSW_START_SEC_VAR_SAVED_RECOVERY_ZONE_8
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_VAR_SAVED_RECOVERY_ZONE_8
    #undef BSW_STOP_SEC_VAR_SAVED_RECOVERY_ZONE_8
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_VAR_SAVED_RECOVERY_ZONE_16
    #undef BSW_START_SEC_VAR_SAVED_RECOVERY_ZONE_16
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_VAR_SAVED_RECOVERY_ZONE_16
    #undef BSW_STOP_SEC_VAR_SAVED_RECOVERY_ZONE_16
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_VAR_SAVED_RECOVERY_ZONE_32
    #undef BSW_START_SEC_VAR_SAVED_RECOVERY_ZONE_32
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_VAR_SAVED_RECOVERY_ZONE_32
    #undef BSW_STOP_SEC_VAR_SAVED_RECOVERY_ZONE_32
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_START_SEC_VAR_SAVED_RECOVERY_ZONE_UNSPECIFIED
    #undef BSW_START_SEC_VAR_SAVED_RECOVERY_ZONE_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_VAR_SAVED_RECOVERY_ZONE_UNSPECIFIED
    #undef BSW_STOP_SEC_VAR_SAVED_RECOVERY_ZONE_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR
//*****************************************************************************

//*****************************************************************************
// <MODULE>_START_SEC_CODE
// <MODULE>_STOP_SEC_CODE
//*****************************************************************************
#elif defined BSW_START_SEC_CODE
    #undef BSW_START_SEC_CODE
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_CODE
    #undef BSW_STOP_SEC_CODE
    #undef BSW_MEMMAP_ERROR
//*****************************************************************************

//*****************************************************************************
// <MODULE>_START_SEC_CODE_FAST
// <MODULE>_STOP_SEC_CODE_FAST
//*****************************************************************************
#elif defined BSW_START_SEC_CODE_FAST
    #undef BSW_START_SEC_CODE_FAST
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_CODE_FAST
    #undef BSW_STOP_SEC_CODE_FAST
    #undef BSW_MEMMAP_ERROR
//*****************************************************************************

//*****************************************************************************
// <MODULE>_START_SEC_CODE_SLOW
// <MODULE>_STOP_SEC_CODE_SLOW
//*****************************************************************************
#elif defined BSW_START_SEC_CODE_SLOW
    #undef BSW_START_SEC_CODE_SLOW
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_CODE_SLOW
    #undef BSW_STOP_SEC_CODE_SLOW
    #undef BSW_MEMMAP_ERROR
//*****************************************************************************

//*****************************************************************************
// <MODULE>_START_SEC_CODE_LIB
// <MODULE>_STOP_SEC_CODE_LIB
//*****************************************************************************
#elif defined BSW_START_SEC_CODE_LIB
    #undef BSW_START_SEC_CODE_LIB
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_CODE_LIB
    #undef BSW_STOP_SEC_CODE_LIB
    #undef BSW_MEMMAP_ERROR
//*****************************************************************************

//*****************************************************************************
// <MODULE>_START_SEC_CALLOUT_CODE_SLOW
// <MODULE>_STOP_SEC_CALLOUT_CODE_SLOW
//*****************************************************************************
#elif defined BSW_START_SEC_CALLOUT_CODE_SLOW
    #undef BSW_START_SEC_CALLOUT_CODE_SLOW
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_CALLOUT_CODE_SLOW
    #undef BSW_STOP_SEC_CALLOUT_CODE_SLOW
    #undef BSW_MEMMAP_ERROR
//*****************************************************************************






//*****************************************************************************
// legacy (old content of BSW_MemMap, not following the coding guidelines
//*****************************************************************************
/* ============================   BSW   ============================ */

#elif defined BSW_START_SEC_DEFAULT_RAM0_CLEARED_8
    #undef BSW_START_SEC_DEFAULT_RAM0_CLEARED_8
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_DEFAULT_RAM0_CLEARED_8
    #undef BSW_STOP_SEC_DEFAULT_RAM0_CLEARED_8
    #undef BSW_MEMMAP_ERROR

#elif defined BSW_START_SEC_DEFAULT_RAM0_CLEARED_16
    #undef BSW_START_SEC_DEFAULT_RAM0_CLEARED_16
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_DEFAULT_RAM0_CLEARED_16
    #undef BSW_STOP_SEC_DEFAULT_RAM0_CLEARED_16
    #undef BSW_MEMMAP_ERROR

#elif defined BSW_START_SEC_DEFAULT_RAM0_CLEARED_32
    #undef BSW_START_SEC_DEFAULT_RAM0_CLEARED_32
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_DEFAULT_RAM0_CLEARED_32
    #undef BSW_STOP_SEC_DEFAULT_RAM0_CLEARED_32
    #undef BSW_MEMMAP_ERROR

#elif defined BSW_START_SEC_DEFAULT_RAM0_CLEARED_UNSPECIFIED
    #undef BSW_START_SEC_DEFAULT_RAM0_CLEARED_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_DEFAULT_RAM0_CLEARED_UNSPECIFIED
    #undef BSW_STOP_SEC_DEFAULT_RAM0_CLEARED_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR

#elif defined BSW_START_SEC_DEFAULT_RAM1_CLEARED_8
    #undef BSW_START_SEC_DEFAULT_RAM1_CLEARED_8
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_DEFAULT_RAM1_CLEARED_8
    #undef BSW_STOP_SEC_DEFAULT_RAM1_CLEARED_8
    #undef BSW_MEMMAP_ERROR

#elif defined BSW_START_SEC_DEFAULT_RAM1_CLEARED_16
    #undef BSW_START_SEC_DEFAULT_RAM1_CLEARED_16
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_DEFAULT_RAM1_CLEARED_16
    #undef BSW_STOP_SEC_DEFAULT_RAM1_CLEARED_16
    #undef BSW_MEMMAP_ERROR

#elif defined BSW_START_SEC_DEFAULT_RAM1_CLEARED_32
    #undef BSW_START_SEC_DEFAULT_RAM1_CLEARED_32
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_DEFAULT_RAM1_CLEARED_32
    #undef BSW_STOP_SEC_DEFAULT_RAM1_CLEARED_32
    #undef BSW_MEMMAP_ERROR

#elif defined BSW_START_SEC_DEFAULT_RAM1_CLEARED_UNSPECIFIED
    #undef BSW_START_SEC_DEFAULT_RAM1_CLEARED_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR

#elif defined BSW_STOP_SEC_DEFAULT_RAM1_CLEARED_UNSPECIFIED
    #undef BSW_STOP_SEC_DEFAULT_RAM1_CLEARED_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR

#elif defined BSW_START_SEC_DEFAULT_RAM2_CLEARED_8
    #undef BSW_START_SEC_DEFAULT_RAM2_CLEARED_8
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_DEFAULT_RAM2_CLEARED_8
    #undef BSW_STOP_SEC_DEFAULT_RAM2_CLEARED_8
    #undef BSW_MEMMAP_ERROR

#elif defined BSW_START_SEC_DEFAULT_RAM2_CLEARED_16
    #undef BSW_START_SEC_DEFAULT_RAM2_CLEARED_16
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_DEFAULT_RAM2_CLEARED_16
    #undef BSW_STOP_SEC_DEFAULT_RAM2_CLEARED_16
    #undef BSW_MEMMAP_ERROR

#elif defined BSW_START_SEC_DEFAULT_RAM2_CLEARED_32
    #undef BSW_START_SEC_DEFAULT_RAM2_CLEARED_32
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_DEFAULT_RAM2_CLEARED_32
    #undef BSW_STOP_SEC_DEFAULT_RAM2_CLEARED_32
    #undef BSW_MEMMAP_ERROR

#elif defined BSW_START_SEC_DEFAULT_RAM2_CLEARED_UNSPECIFIED
    #undef BSW_START_SEC_DEFAULT_RAM2_CLEARED_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_DEFAULT_RAM2_CLEARED_UNSPECIFIED
    #undef BSW_STOP_SEC_DEFAULT_RAM2_CLEARED_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR

#elif defined BSW_START_SEC_SMALL_RAM0_CLEARED_8
    #undef BSW_START_SEC_SMALL_RAM0_CLEARED_8
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_SMALL_RAM0_CLEARED_8
    #undef BSW_STOP_SEC_SMALL_RAM0_CLEARED_8
    #undef BSW_MEMMAP_ERROR

#elif defined BSW_START_SEC_SMALL_RAM0_CLEARED_16
    #undef BSW_START_SEC_SMALL_RAM0_CLEARED_16
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_SMALL_RAM0_CLEARED_16
    #undef BSW_STOP_SEC_SMALL_RAM0_CLEARED_16
    #undef BSW_MEMMAP_ERROR

#elif defined BSW_START_SEC_SMALL_RAM0_CLEARED_32
    #undef BSW_START_SEC_SMALL_RAM0_CLEARED_32
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_SMALL_RAM0_CLEARED_32
    #undef BSW_STOP_SEC_SMALL_RAM0_CLEARED_32
    #undef BSW_MEMMAP_ERROR

#elif defined BSW_START_SEC_SMALL_RAM0_CLEARED_UNSPECIFIED
    #undef BSW_START_SEC_SMALL_RAM0_CLEARED_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_SMALL_RAM0_CLEARED_UNSPECIFIED
    #undef BSW_STOP_SEC_SMALL_RAM0_CLEARED_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR

#elif defined BSW_START_SEC_SMALL_RAM1_CLEARED_8
    #undef BSW_START_SEC_SMALL_RAM1_CLEARED_8
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_SMALL_RAM1_CLEARED_8
    #undef BSW_STOP_SEC_SMALL_RAM1_CLEARED_8
    #undef BSW_MEMMAP_ERROR

#elif defined BSW_START_SEC_SMALL_RAM1_CLEARED_16
    #undef BSW_START_SEC_SMALL_RAM1_CLEARED_16
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_SMALL_RAM1_CLEARED_16
    #undef BSW_STOP_SEC_SMALL_RAM1_CLEARED_16
    #undef BSW_MEMMAP_ERROR

#elif defined BSW_START_SEC_SMALL_RAM1_CLEARED_32
    #undef BSW_START_SEC_SMALL_RAM1_CLEARED_32
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_SMALL_RAM1_CLEARED_32
    #undef BSW_STOP_SEC_SMALL_RAM1_CLEARED_32
    #undef BSW_MEMMAP_ERROR

#elif defined BSW_START_SEC_SMALL_RAM1_CLEARED_UNSPECIFIED
    #undef BSW_START_SEC_SMALL_RAM1_CLEARED_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_SMALL_RAM1_CLEARED_UNSPECIFIED
    #undef BSW_STOP_SEC_SMALL_RAM1_CLEARED_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR

#elif defined BSW_START_SEC_SMALL_RAM2_CLEARED_8
    #undef BSW_START_SEC_SMALL_RAM2_CLEARED_8
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_SMALL_RAM2_CLEARED_8
    #undef BSW_STOP_SEC_SMALL_RAM2_CLEARED_8
    #undef BSW_MEMMAP_ERROR

#elif defined BSW_START_SEC_SMALL_RAM2_CLEARED_16
    #undef BSW_START_SEC_SMALL_RAM2_CLEARED_16
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_SMALL_RAM2_CLEARED_16
    #undef BSW_STOP_SEC_SMALL_RAM2_CLEARED_16
    #undef BSW_MEMMAP_ERROR

#elif defined BSW_START_SEC_SMALL_RAM2_CLEARED_32
    #undef BSW_START_SEC_SMALL_RAM2_CLEARED_32
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_SMALL_RAM2_CLEARED_32
    #undef BSW_STOP_SEC_SMALL_RAM2_CLEARED_32
    #undef BSW_MEMMAP_ERROR

#elif defined BSW_START_SEC_SMALL_RAM2_CLEARED_UNSPECIFIED
    #undef BSW_START_SEC_SMALL_RAM2_CLEARED_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_SMALL_RAM2_CLEARED_UNSPECIFIED
    #undef BSW_STOP_SEC_SMALL_RAM2_CLEARED_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR

#elif defined BSW_START_SEC_DEFAULT_RAM0_INIT_8
    #undef BSW_START_SEC_DEFAULT_RAM0_INIT_8
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_DEFAULT_RAM0_INIT_8
    #undef BSW_STOP_SEC_DEFAULT_RAM0_INIT_8
    #undef BSW_MEMMAP_ERROR

#elif defined BSW_START_SEC_DEFAULT_RAM0_INIT_16
    #undef BSW_START_SEC_DEFAULT_RAM0_INIT_16
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_DEFAULT_RAM0_INIT_16
    #undef BSW_STOP_SEC_DEFAULT_RAM0_INIT_16
    #undef BSW_MEMMAP_ERROR

#elif defined BSW_START_SEC_DEFAULT_RAM0_INIT_32
    #undef BSW_START_SEC_DEFAULT_RAM0_INIT_32
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_DEFAULT_RAM0_INIT_32
    #undef BSW_STOP_SEC_DEFAULT_RAM0_INIT_32
    #undef BSW_MEMMAP_ERROR

#elif defined BSW_START_SEC_DEFAULT_RAM0_INIT_UNSPECIFIED
    #undef BSW_START_SEC_DEFAULT_RAM0_INIT_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_DEFAULT_RAM0_INIT_UNSPECIFIED
    #undef BSW_STOP_SEC_DEFAULT_RAM0_INIT_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR

#elif defined BSW_START_SEC_DEFAULT_RAM1_INIT_8
    #undef BSW_START_SEC_DEFAULT_RAM1_INIT_8
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_DEFAULT_RAM1_INIT_8
    #undef BSW_STOP_SEC_DEFAULT_RAM1_INIT_8
    #undef BSW_MEMMAP_ERROR

#elif defined BSW_START_SEC_DEFAULT_RAM1_INIT_16
    #undef BSW_START_SEC_DEFAULT_RAM1_INIT_16
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_DEFAULT_RAM1_INIT_16
    #undef BSW_STOP_SEC_DEFAULT_RAM1_INIT_16
    #undef BSW_MEMMAP_ERROR

#elif defined BSW_START_SEC_DEFAULT_RAM1_INIT_32
    #undef BSW_START_SEC_DEFAULT_RAM1_INIT_32
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_DEFAULT_RAM1_INIT_32
    #undef BSW_STOP_SEC_DEFAULT_RAM1_INIT_32
    #undef BSW_MEMMAP_ERROR

#elif defined BSW_START_SEC_DEFAULT_RAM1_INIT_UNSPECIFIED
    #undef BSW_START_SEC_DEFAULT_RAM1_INIT_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_DEFAULT_RAM1_INIT_UNSPECIFIED
    #undef BSW_STOP_SEC_DEFAULT_RAM1_INIT_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR

#elif defined BSW_START_SEC_DEFAULT_RAM2_INIT_8
    #undef BSW_START_SEC_DEFAULT_RAM2_INIT_8
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_DEFAULT_RAM2_INIT_8
    #undef BSW_STOP_SEC_DEFAULT_RAM2_INIT_8
    #undef BSW_MEMMAP_ERROR

#elif defined BSW_START_SEC_DEFAULT_RAM2_INIT_16
    #undef BSW_START_SEC_DEFAULT_RAM2_INIT_16
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_DEFAULT_RAM2_INIT_16
    #undef BSW_STOP_SEC_DEFAULT_RAM2_INIT_16
    #undef BSW_MEMMAP_ERROR

#elif defined BSW_START_SEC_DEFAULT_RAM2_INIT_32
    #undef BSW_START_SEC_DEFAULT_RAM2_INIT_32
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_DEFAULT_RAM2_INIT_32
    #undef BSW_STOP_SEC_DEFAULT_RAM2_INIT_32
    #undef BSW_MEMMAP_ERROR

#elif defined BSW_START_SEC_DEFAULT_RAM2_INIT_UNSPECIFIED
    #undef BSW_START_SEC_DEFAULT_RAM2_INIT_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_DEFAULT_RAM2_INIT_UNSPECIFIED
    #undef BSW_STOP_SEC_DEFAULT_RAM2_INIT_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR

#elif defined BSW_START_SEC_SMALL_RAM0_INIT_8
    #undef BSW_START_SEC_SMALL_RAM0_INIT_8
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_SMALL_RAM0_INIT_8
    #undef BSW_STOP_SEC_SMALL_RAM0_INIT_8
    #undef BSW_MEMMAP_ERROR

#elif defined BSW_START_SEC_SMALL_RAM0_INIT_16
    #undef BSW_START_SEC_SMALL_RAM0_INIT_16
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_SMALL_RAM0_INIT_16
    #undef BSW_STOP_SEC_SMALL_RAM0_INIT_16
    #undef BSW_MEMMAP_ERROR

#elif defined BSW_START_SEC_SMALL_RAM0_INIT_32
    #undef BSW_START_SEC_SMALL_RAM0_INIT_32
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_SMALL_RAM0_INIT_32
    #undef BSW_STOP_SEC_SMALL_RAM0_INIT_32
    #undef BSW_MEMMAP_ERROR

#elif defined BSW_START_SEC_SMALL_RAM0_INIT_UNSPECIFIED
    #undef BSW_START_SEC_SMALL_RAM0_INIT_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_SMALL_RAM0_INIT_UNSPECIFIED
    #undef BSW_STOP_SEC_SMALL_RAM0_INIT_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR

#elif defined BSW_START_SEC_SMALL_RAM1_INIT_8
    #undef BSW_START_SEC_SMALL_RAM1_INIT_8
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_SMALL_RAM1_INIT_8
    #undef BSW_STOP_SEC_SMALL_RAM1_INIT_8
    #undef BSW_MEMMAP_ERROR

#elif defined BSW_START_SEC_SMALL_RAM1_INIT_16
    #undef BSW_START_SEC_SMALL_RAM1_INIT_16
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_SMALL_RAM1_INIT_16
    #undef BSW_STOP_SEC_SMALL_RAM1_INIT_16
    #undef BSW_MEMMAP_ERROR

#elif defined BSW_START_SEC_SMALL_RAM1_INIT_32
    #undef BSW_START_SEC_SMALL_RAM1_INIT_32
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_SMALL_RAM1_INIT_32
    #undef BSW_STOP_SEC_SMALL_RAM1_INIT_32
    #undef BSW_MEMMAP_ERROR

#elif defined BSW_START_SEC_SMALL_RAM1_INIT_UNSPECIFIED
    #undef BSW_START_SEC_SMALL_RAM1_INIT_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_SMALL_RAM1_INIT_UNSPECIFIED
    #undef BSW_STOP_SEC_SMALL_RAM1_INIT_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR

#elif defined BSW_START_SEC_SMALL_RAM2_INIT_8
    #undef BSW_START_SEC_SMALL_RAM2_INIT_8
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_SMALL_RAM2_INIT_8
    #undef BSW_STOP_SEC_SMALL_RAM2_INIT_8
    #undef BSW_MEMMAP_ERROR

#elif defined BSW_START_SEC_SMALL_RAM2_INIT_16
    #undef BSW_START_SEC_SMALL_RAM2_INIT_16
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_SMALL_RAM2_INIT_16
    #undef BSW_STOP_SEC_SMALL_RAM2_INIT_16
    #undef BSW_MEMMAP_ERROR

#elif defined BSW_START_SEC_SMALL_RAM2_INIT_32
    #undef BSW_START_SEC_SMALL_RAM2_INIT_32
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_SMALL_RAM2_INIT_32
    #undef BSW_STOP_SEC_SMALL_RAM2_INIT_32
    #undef BSW_MEMMAP_ERROR

#elif defined BSW_START_SEC_SMALL_RAM2_INIT_UNSPECIFIED
    #undef BSW_START_SEC_SMALL_RAM2_INIT_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_SMALL_RAM2_INIT_UNSPECIFIED
    #undef BSW_STOP_SEC_SMALL_RAM2_INIT_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR

#elif defined BSW_START_SEC_SMALL_SYSRAM_CLEARED_8
    #undef BSW_START_SEC_SMALL_SYSRAM_CLEARED_8
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_SMALL_SYSRAM_CLEARED_8
    #undef BSW_STOP_SEC_SMALL_SYSRAM_CLEARED_8
    #undef BSW_MEMMAP_ERROR

#elif defined BSW_START_SEC_SMALL_SYSRAM_CLEARED_16
    #undef BSW_START_SEC_SMALL_SYSRAM_CLEARED_16
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_SMALL_SYSRAM_CLEARED_16
    #undef BSW_STOP_SEC_SMALL_SYSRAM_CLEARED_16
    #undef BSW_MEMMAP_ERROR

#elif defined BSW_START_SEC_SMALL_SYSRAM_CLEARED_32
    #undef BSW_START_SEC_SMALL_SYSRAM_CLEARED_32
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_SMALL_SYSRAM_CLEARED_32
    #undef BSW_STOP_SEC_SMALL_SYSRAM_CLEARED_32
    #undef BSW_MEMMAP_ERROR

#elif defined BSW_START_SEC_SMALL_SYSRAM_CLEARED_UNSPECIFIED
    #undef BSW_START_SEC_SMALL_SYSRAM_CLEARED_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_SMALL_SYSRAM_CLEARED_UNSPECIFIED
    #undef BSW_STOP_SEC_SMALL_SYSRAM_CLEARED_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR

#elif defined BSW_START_SEC_DEFAULT_SYSRAM_CLEARED_8
    #undef BSW_START_SEC_DEFAULT_SYSRAM_CLEARED_8
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_DEFAULT_SYSRAM_CLEARED_8
    #undef BSW_STOP_SEC_DEFAULT_SYSRAM_CLEARED_8
    #undef BSW_MEMMAP_ERROR

#elif defined BSW_START_SEC_DEFAULT_SYSRAM_CLEARED_16
    #undef BSW_START_SEC_DEFAULT_SYSRAM_CLEARED_16
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_DEFAULT_SYSRAM_CLEARED_16
    #undef BSW_STOP_SEC_DEFAULT_SYSRAM_CLEARED_16
    #undef BSW_MEMMAP_ERROR

#elif defined BSW_START_SEC_DEFAULT_SYSRAM_CLEARED_32
    #undef BSW_START_SEC_DEFAULT_SYSRAM_CLEARED_32
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_DEFAULT_SYSRAM_CLEARED_32
    #undef BSW_STOP_SEC_DEFAULT_SYSRAM_CLEARED_32
    #undef BSW_MEMMAP_ERROR

#elif defined BSW_START_SEC_DEFAULT_SYSRAM_CLEARED_UNSPECIFIED
    #undef BSW_START_SEC_DEFAULT_SYSRAM_CLEARED_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_DEFAULT_SYSRAM_CLEARED_UNSPECIFIED
    #undef BSW_STOP_SEC_DEFAULT_SYSRAM_CLEARED_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR

#elif defined BSW_START_SEC_DEFAULT_ENVRAM_8
    #undef BSW_START_SEC_DEFAULT_ENVRAM_8
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_DEFAULT_ENVRAM_8
    #undef BSW_STOP_SEC_DEFAULT_ENVRAM_8
    #undef BSW_MEMMAP_ERROR

#elif defined BSW_START_SEC_DEFAULT_ENVRAM_16
    #undef BSW_START_SEC_DEFAULT_ENVRAM_16
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_DEFAULT_ENVRAM_16
    #undef BSW_STOP_SEC_DEFAULT_ENVRAM_16
    #undef BSW_MEMMAP_ERROR

#elif defined BSW_START_SEC_DEFAULT_ENVRAM_32
    #undef BSW_START_SEC_DEFAULT_ENVRAM_32
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_DEFAULT_ENVRAM_32
    #undef BSW_STOP_SEC_DEFAULT_ENVRAM_32
    #undef BSW_MEMMAP_ERROR

#elif defined BSW_START_SEC_DEFAULT_ENVRAM_UNSPECIFIED
    #undef BSW_START_SEC_DEFAULT_ENVRAM_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_DEFAULT_ENVRAM_UNSPECIFIED
    #undef BSW_STOP_SEC_DEFAULT_ENVRAM_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR

#elif defined BSW_START_SEC_DEFAULT_CONST_8
    #undef BSW_START_SEC_DEFAULT_CONST_8
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_DEFAULT_CONST_8
    #undef BSW_STOP_SEC_DEFAULT_CONST_8
    #undef BSW_MEMMAP_ERROR

#elif defined BSW_START_SEC_DEFAULT_CONST_16
    #undef BSW_START_SEC_DEFAULT_CONST_16
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_DEFAULT_CONST_16
    #undef BSW_STOP_SEC_DEFAULT_CONST_16
    #undef BSW_MEMMAP_ERROR

#elif defined BSW_START_SEC_DEFAULT_CONST_32
    #undef BSW_START_SEC_DEFAULT_CONST_32
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_DEFAULT_CONST_32
    #undef BSW_STOP_SEC_DEFAULT_CONST_32
    #undef BSW_MEMMAP_ERROR

#elif defined BSW_START_SEC_DEFAULT_CONST_UNSPECIFIED
    #undef BSW_START_SEC_DEFAULT_CONST_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_DEFAULT_CONST_UNSPECIFIED
    #undef BSW_STOP_SEC_DEFAULT_CONST_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR

#elif defined BSW_START_SEC_DEFAULT_CALIB_8
    #undef BSW_START_SEC_DEFAULT_CALIB_8
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_DEFAULT_CALIB_8
    #undef BSW_STOP_SEC_DEFAULT_CALIB_8
    #undef BSW_MEMMAP_ERROR

#elif defined BSW_START_SEC_DEFAULT_CALIB_16
    #undef BSW_START_SEC_DEFAULT_CALIB_16
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_DEFAULT_CALIB_16
    #undef BSW_STOP_SEC_DEFAULT_CALIB_16
    #undef BSW_MEMMAP_ERROR

#elif defined BSW_START_SEC_DEFAULT_CALIB_32
    #undef BSW_START_SEC_DEFAULT_CALIB_32
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_DEFAULT_CALIB_32
    #undef BSW_STOP_SEC_DEFAULT_CALIB_32
    #undef BSW_MEMMAP_ERROR

#elif defined BSW_START_SEC_DEFAULT_CALIB_UNSPECIFIED
    #undef BSW_START_SEC_DEFAULT_CALIB_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_DEFAULT_CALIB_UNSPECIFIED
    #undef BSW_STOP_SEC_DEFAULT_CALIB_UNSPECIFIED
    #undef BSW_MEMMAP_ERROR

#elif defined BSW_START_SEC_SPRAM_CODE
    #undef BSW_START_SEC_SPRAM_CODE
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_SPRAM_CODE
    #undef BSW_STOP_SEC_SPRAM_CODE
    #undef BSW_MEMMAP_ERROR

#elif defined BSW_START_SEC_DEFAULT_CODE
    #undef BSW_START_SEC_DEFAULT_CODE
    #undef BSW_MEMMAP_ERROR
#elif defined BSW_STOP_SEC_DEFAULT_CODE
    #undef BSW_STOP_SEC_DEFAULT_CODE
    #undef BSW_MEMMAP_ERROR
//*****************************************************************************


#elif defined BSW_MEMMAP_ERROR
    #error "Bsw_MemMap.h, wrong #pragma command"
#endif
